<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->

<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
  <h3 class="sidebar">Helpful links</h3>
  <div class="quick_links">
    <ul class="fa-ul">
      <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="/hr/womens-network/steering-committee.htm">Women's Network Steering Committee</a></li>
      <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://qheps.health.qld.gov.au/comms/awlsummit/html/awlsummit-2016.htm">Aspiring Women Leaders' Summit 2016</a> (videos)</li>
      <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://qheps.health.qld.gov.au/comms/awlsummit/html/awlsummit-2015.htm">Aspiring Women Leaders' Summit 2015</a> (videos)</li>
    </ul>
  </div>
</div>
<!-- END Quick Links section -->

<!-- BEGIN Contact section -->
<div class="sidebar_section">
  <h3 class="sidebar">Need more help?</h3>
  <div class="quick_links">
    <ul class="fa-ul">
      <li>
        <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="/hr/contact/local-hr-contacts.htm">Contact your local HR</a></strong>
      </li>
    </ul>
  </div>
</div>
<!-- END Contact section -->
