<div class="promo-image"><a href="http://qheps.health.qld.gov.au/streamline/"><img src="/paris/images/pss-button.jpg" alt="Streamline Online services for staff" class="image-button"/></a>
    <br>
    <a href="http://qheps.health.qld.gov.au/payroll-assistance/"><img src="/paris/images/payroll-portfolio.jpg" alt="Payroll Portfolio" class="image-button"/></a>
    <br>
    <a href="http://qheps.health.qld.gov.au/payroll-assistance/html/myHR.htm"><img src="/paris/images/myhr-button-image.jpg" alt="myHR" class="image-button"/></a></div>
<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Popular pages section -->
<div class="sidebar_section">
    <h3 class="sidebar">Popular pages</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/paris/forms/home.htm">Payroll and rostering A&ndash;Z forms</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/paris/forms/avac.htm">Attendance variations</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/paris/managers/payslip-messages.htm">Payslip messages</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/paris/calendar/home.htm">Calendars</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/payroll-assistance/html/contacts.htm">Payroll Portfolio contacts</a></li>
        </ul>
    </div>
</div>
<!-- END Supporting resources section -->
<!-- BEGIN Related links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/employment-conditions/policies-index.htm">HR policies index</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/employment-conditions/wage-rates.htm">Wage rates</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/employment-conditions/awards-agreements.htm">Awards and agreements</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.ato.gov.au/">Australian Tax Office</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://streamline.health.qld.gov.au/content/help/glossary-of-terms.pdf">Payroll glossary of terms</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/qhpp/html/overpayments.htm">Overpayments</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://qsuper.qld.gov.au/">QSuper</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.psc.qld.gov.au/publications/directives.aspx">Public Service Commission directives</a></li>
        </ul>
    </div>
</div>
<!-- END Related links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-phone fa-lg" aria-hidden="true"></i>Call the Payroll hotline <a href="tel:1800239074">1800 239 074</a>
                <!-- Customise with sub-site contact's direct email -->
            </li>
            <li>
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><strong><a href="mailto:HRBusinessRequirements@health.qld.gov.au">email HR Business Requirements</a></strong>
                <!-- Customise with sub-site contact's direct email -->
            </li>
            <li><i class="fa-li fa fa-envelope fa-lg " aria-hidden="true "></i><a href="mailto:HRConnect@health.qld.gov.au">Email HR Connect</a></li>
        </ul>
    </div>
</div>
<!-- END Contact section -->