<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Related Links section-->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-calendar-check-o fa-lg" aria-hidden="true"></i>
                <a href="/hr/learning/training-calendar.htm">Training calendar</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i>
                <a href="/hr/culture/home.htm">Our culture</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i>
                <a href="/governance/corporategovernance/home.htm">Corporate governance</a></li>
        </ul>
    </div>
</div>
<!--END Related Links section -->
<!-- BEGIN Supporting resources section-->
<div class="sidebar_section">
    <h3 class="sidebar">Supporting resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i>
                <a href="/hr/docs/training-development/guide-for-managers.pdf">Guide for managers</a> (PDF, 348kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i>
                <a href="/hr/docs/training-development/guide-for-employees.pdf">Guide for employees</a> (PDF, 349kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i>
                <a href="/hr/docs/training-development/70-20-10.pdf">70:20:10 learning model</a> (PDF, 85kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i>
                <a href="/hr/docs/training-development/SMART-goals.pdf">SMART goal setting</a> (PDF, 75kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i>
                <a href="/hr/docs/training-development/conversation-planner.pdf">Conversation planner</a> (PDF, 78kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i>
                <a href="/hr/culture/docs/cultural-success-factors.pdf">Cultural Success Factors</a> (PDF, 435kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i>
                <a href="/hr/docs/training-development/Career-Success-Plan-FAQs.pdf">Career Success Plan FAQs</a> (PDF, 115kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i>
                <a href="/hr/docs/training-development/PCR-strategy.pdf">PCR Strategy</a> (PDF,235kB)</li>
        </ul>
    </div>
</div>
<!--END Supporting resources section -->
<!-- BEGIN CSP Login -->
<div class="sidebar_section">
    <h3 class="sidebar">CSP login</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i>
                <a href="http://vader.bnc.health.qld.gov.au/default.aspx">Login to your CSP</a></li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i>
                <a href="/hr/docs/training-development/technical-guide.pdf">Technical guide</a> (PDF, 989kB)</li>
        </ul>
    </div>
</div>
<!--END CSP Login -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><strong><a href="mailto:CultureCapability@health.qld.gov.au" title="Email us">Email us</a></strong>
                <!-- Customise with sub-site contact's direct email -->
            </li>
            <li>
                <!-- Customise with the sub-site's direct email contact -->
                <i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.yammer.com/health.qld.gov.au/" title="Yammer">Yammer</a>
            </li>
            <li>
                <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="/hr/contact/local-hr-contacts.htm">Contact your local HR</a></strong>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->