<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Related Links section-->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i>
                <a href="/hr/next-generation/home.htm">Next Generation</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i>
                <a href="/hr/mentoring/home.htm">Mentoring</a></li>
            <li><i class="fa-li fa fa-calendar-check-o fa-lg" aria-hidden="true"></i>
                <a href="/hr/learning/training-calendar.htm" title="Training calendar">Training calendar</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i>
                <a href="/hr/culture/home.htm" title="Our culture">Our culture</a></li>
        </ul>
    </div>
</div>
<!--END Related Links section -->
<!-- BEGIN Supporting Links section-->
<div class="sidebar_section">
    <h3 class="sidebar">Supporting resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i>
                <a href="/hr/docs/training-development/capability-dev-framework.pdf" title="Capability Development Framework">Capability Development Framework</a> (PDF, 197kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i>
                <a href="/hr/docs/training-development/70-20-10.pdf" title="70:20:10 learning model">70:20:10 learning model</a> (PDF, 85kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i>
                <a href="/hr/docs/training-development/Career-Success-Plan-FAQs.pdf" title="Career Success Plan FAQs">Career Success Plan FAQs</a> (PDF, 115kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i>
                <a href="/hr/docs/training-development/PCR-strategy.pdf" title="PCR Strategy">PCR Strategy</a> (PDF,235kB)</li>
        </ul>
    </div>
</div>
<!--END Supporting resources section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><strong><a href="mailto:CultureCapability@health.qld.gov.au">Email us</a></strong>
                <!-- Customise with sub-site contact's direct email -->
            </li>
            <li>
                <!-- Customise with the sub-site's direct email contact -->
                <i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.yammer.com/health.qld.gov.au/" title="Yammer">Yammer</a>
            </li>
            <li>
                <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="/hr/contact/local-hr-contacts.htm">Contact your local HR</a></strong>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->