<div id="nav2">
    <a name="sidenav"></a>
    <h3 class="sidebar">Workplace culture</h3>
    <!--beginnoindex-->
    <ul id="nav2xc">
        <li><a href="/hr/culture/home.htm">Our culture</a>
            <ul id="Our culture">
                <li><a href="/hr/culture/our-journey.htm">Our culture journey</a></li>
                <li><a href="/hr/culture/connectedness/home.htm">Connectedness</a></li>
                <li><a href="/hr/culture/performance/home.htm">Performance</a></li>
                <li><a href="/hr/culture/clarity/home.htm">Clarity</a></li>
                <li><a href="/hr/culture/respect/home.htm">Respect</a></li>
                <li><a href="/hr/culture/capability/home.htm">Capability</a></li>
                <li><a href="/hr/culture/resources.htm">Resources</a></li>
                <li><a href="/hr/culture/faqs.htm">FAQs</a></li>
                <li><a href="/hr/culture/sparks/contact-us.htm">Contact us</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li><a href="/hr/culture/sparks/home.htm">Spark network</a>
            <ul id="Spark network">
                <li><a href="/hr/culture/sparks/role.htm">Spark's role</a></li>
                <li><a href="/hr/culture/sparks/initiatives.htm">Spark initiatives</a></li>
                <li><a href="/hr/culture/sparks/contacts.htm">Spark contacts</a></li>
                <li><a href="/hr/culture/sparks/apply.htm">Apply to be a Spark</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li><a href="/hr/diversity-inclusion/home.htm">Diversity, Inclusion &amp; Engagement</a>
            <ul id="Diversity Inclusion &amp; Engagement">
                <li><a href="/hr/diversity-inclusion/strategy.htm">Our strategy</a></li>
                <li><a href="/hr/diversity-inclusion/whats-on.htm">What's new?</a></li>
                <li><a href="/hr/diversity-inclusion/what-is.htm">What is?</a></li>
                <li><a href="/hr/diversity-inclusion/roles-responsibilities.htm">Our roles and responsibilities</a></li>
                <li><a href="/hr/diversity-inclusion/focus-areas/home.htm">Focus areas</a>
                    <br>
                    <div>
                        <a href="/hr/diversity-inclusion/focus-areas/atsi.htm">Aboriginal and Torres Strait Islander peoples</a>
                        <br>
                        <a href="/hr/diversity-inclusion/focus-areas/gender-equity.htm">Gender equity</a>
                        <br>
                        <a href="/hr/diversity-inclusion/focus-areas/lgbtiq.htm">LGBTIQ+</a>
                        <br>
                        <a href="/hr/diversity-inclusion/focus-areas/disability.htm">People with a disability</a>
                        <br>
                        <a href="/hr/diversity-inclusion/focus-areas/speaking-background.htm">People from a non-English speaking background</a>
                        <br>
                        <a href="/hr/diversity-inclusion/focus-areas/youth.htm">Youth (under 25)</a>
                        <br>
                        <a href="/hr/diversity-inclusion/focus-areas/mature.htm">Mature (over 45)</a>
                    </div>
                </li>
                <li><a href="/hr/diversity-inclusion/key-dates.htm">Key dates</a></li>
                <li><a href="/hr/campaigns/human-rights-month/home.htm">Age friendly workplaces</a></li>
                <li><a href="/hr/diversity-inclusion/committee.htm">The committee</a></li>
                <li><a href="/hr/diversity-inclusion/supporting-resources.htm">Supporting resources</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li><a href="/hr/workplace-culture/working-for-queensland-survey/home.htm">Working for Queensland Survey</a>
            <ul id="Working for Queensland Survey">
                <li><a href="/hr/workplace-culture/working-for-queensland-survey/key-highlights.htm">Key highlights</a></li>
                <li><a href="/hr/workplace-culture/working-for-queensland-survey/our-way-forward.htm">Our way forward</a></li>
                <li><a href="/hr/workplace-culture/working-for-queensland-survey/anonymity.htm">Anonymity</a></li>
                <li><a href="/hr/workplace-culture/working-for-queensland-survey/advice.htm">Advice</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li><a href="/hr/workplace-culture/code-of-conduct/home.htm">Code of conduct</a></li>
        <!--endnoindex-->
        <li><a href="/hr/employee-complaints/home.htm">Employee complaints</a>
            <ul id="Employee Complaints">
                <li><a href="/hr/employee-complaints/sexual-harassment/home.htm">Sexual harassment</a></li>
                <li><a href="/hr/employee-complaints/workplace-harassment/home.htm">Workplace harassment</a></li>
                <li><a href="/hr/employee-complaints/workplace-discrimination/home.htm">Workplace discrimination</a></li>
                <li><a href="/hr/concerns-complaints/whs.htm">Workplace health and safety</a></li>
                <li><a href="/hr/corrupt-conduct/home.htm">Corrupt conduct</a></li>
                <li><a href="/hr/corrupt-conduct/criminal-matters.htm">Criminal matters</a></li>
                <li><a href="/hr/employee-complaints/resources.htm">Guides and resources</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li></li>
        <!--blank spacer. needed as QHEPS shell table styles conflict with custom styles here -->
    </ul>
</div>