<div id="nav2">
    <a name="sidenav"></a>
    <h3 class="sidebar">In this section</h3>
    <!--beginnoindex-->
    <ul id="nav2xc">

        <li><a href="/hr/diversity-inclusion/home.htm">Diversity, Inclusion &amp; Engagement</a>

        </li>

        <!--endnoindex-->

        <li><a href="/hr/diversity-inclusion/whats-on.htm">What's on?</a>

        </li>

        <!--endnoindex-->

        <li><a href="/hr/diversity-inclusion/what-is.htm">What is?</a>

        </li>

        <!--endnoindex-->

        <li><a href="/hr/diversity-inclusion/roles-responsibilities.htm">Our roles and responsibilities</a>

        </li>

        <!--endnoindex-->
	
	<li><a href="/hr/diversity-inclusion/diversity-data.htm">Diversity data</a>

        </li>

        <!--endnoindex-->

        <li class="xc">
            <a href="/hr/diversity-inclusion/focus-areas/home.htm">Focus areas</a>

            <ul id="Focus areas" style="display: none;">

                <li><a href="/hr/diversity-inclusion/focus-areas/atsi.htm">Aboriginal and Torres Strait Islander peoples</a></li>

                <li><a href="/hr/diversity-inclusion/focus-areas/gender-equity.htm">Gender equity</a></li>

                <li><a href="/hr/diversity-inclusion/focus-areas/lgbtiq.htm">LGBTIQ+</a></li>

                <li><a href="/hr/diversity-inclusion/focus-areas/disability.htm">People with a disability</a></li>

                <li><a href="/hr/diversity-inclusion/focus-areas/speaking-background.htm">People from a non-English speaking background</a></li>

                <li><a href="/hr/diversity-inclusion/focus-areas/youth.htm">Youth (under 25)</a></li>

                <li><a href="/hr/diversity-inclusion/focus-areas/mature.htm">Mature (over 45)</a></li>

            </ul>
        </li>

        <!--endnoindex-->

        <li><a href="/hr/diversity-inclusion/key-dates.htm">Key dates</a></li>

        <!--endnoindex-->

        <li><a href="mailto:diversity.inclusion@health.qld.gov.au">Contact us</a></li>

        <!--endnoindex-->

    </ul>
</div>
