<div id="nav2">
	<a name="sidenav"></a>
	<!-- BEGIN Quick Links section -->
	<div class="sidebar_section">
		<h3 class="sidebar">Popular pages</h3>
		<div class="quick_links">
			<ul class="fa-ul">
				<li>
					<i class="fa-li fa fa-file-o fa-lg" aria-hidden="true"></i><a href="/paris/forms/">Forms index</a></li>
				<li>
					<i class="fa-li fa fa-file-o fa-lg" aria-hidden="true"></i><a href="/hr/pay-leave-benefits/wage-rates/">Wage rates</a></li>
				<li>
					<i class="fa-li fa fa-file-o fa-lg" aria-hidden="true"></i><a href="/paris/employees/leave.htm">Leave processes</a></li>
				<li>
					<i class="fa-li fa fa-file-o fa-lg" aria-hidden="true"></i><a href="/paris/forms/avac.htm">Attendance Variation (AVAC)</a></li>
				<li>
					<i class="fa-li fa fa-file-o fa-lg" aria-hidden="true"></i><a href="/hr/policies-agreements-directives/policy-index/">Policy index</a></li>
			</ul>
		</div>
	</div>
	<!-- END Quick Links section -->

	<!-- BEGIN Quick Links section -->
	<div class="sidebar_section">
		<h3 class="sidebar">Popular resources</h3>
		<div class="quick_links">
			<ul class="fa-ul">
				<li>
					<i class="fa-li fa fa-wpforms fa-lg" aria-hidden="true"></i><a href="/paris/">PARIS</a></li>
				<li>
					<i class="fa-li fa fa-dollar fa-lg" aria-hidden="true"></i><a href="/streamline/">Streamline</a></li>
				<li>
					<i class="fa-li fa fa-graduation-cap fa-lg" aria-hidden="true"></i><a href="/ilearn/">iLearn</a></li>
				<li>
					<i class="fa-li fa fa-medkit fa-lg" aria-hidden="true"></i><a href="http://qheps.health.qld.gov.au/safety/employees/incident_reporting.htm">Incident reporting</a></li>
				<li>
					<i class="fa-li fa fa-group fa-lg" aria-hidden="true"></i><a href="/hr/recruitment/">Recruitment</a></li>
				<li>
					<i class="fa-li fa fa-support fa-lg" aria-hidden="true"></i><a href="/hr/staff-health-wellbeing/counselling-support/home.htm">Counselling and support</a></li>
			</ul>
		</div>
	</div>
	<!-- END Quick Links section -->

	<!-- BEGIN Quick Links section -->
	<div class="sidebar_section">
		<h3 class="sidebar">Popular downloads</h3>
		<div class="quick_links">
			<ul class="fa-ul">
				<li>
					<i class="fa-li fa fa-download fa-lg" aria-hidden="true"></i><a href="http://qheps.health.qld.gov.au/paris/pdfs/forms/hr_leave_app.pdf">Leave form</a></li>
				<li>
					<i class="fa-li fa fa-download fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/__data/assets/pdf_file/0034/635893/qh-pol-212.pdf">Recruitment and Selection policy</a></li>
				<li>
					<i class="fa-li fa fa-download fa-lg" aria-hidden="true"></i><a href="http://qheps.health.qld.gov.au/paris/pdfs/forms/hr_attvar_allow_avac.pdf">Attendance variation form</a></li>
				<li>
					<i class="fa-li fa fa-download fa-lg" aria-hidden="true"></i><a href="http://qheps.health.qld.gov.au/paris/pdfs/forms/hr_emp_mov_high_dut.pdf">Employee movement form</a></li>
				<li>
					<i class="fa-li fa fa-download fa-lg" aria-hidden="true"></i><a href="http://qheps.health.qld.gov.au/paris/reporting/docs/form-daily-staffvariance.pdf">Daily staffing variance form</a></li>
			</ul>
		</div>
	</div>
	<!-- END Quick Links section -->
</div>
