<!--[if lt IE 8]>
<div class="alert-box danger css-table">
    <div class="col"><i class="fa fa-warning fa-4x pull-left"></i></div>
    <div class="col">
        <p class="alert-title danger">Warning!</p>
        <p>The QHEPS site does not correctly support Internet Explorer. For best experience please use <a href="https://www.mozilla.org/en-US/firefox/new/">Firefox</a>, <a href="http://google.com/chrome">Chrome</a> or Safari.</p>
    </div>
</div>
 <![endif]-->
