<div id="nav2">
    <a name="sidenav"></a>
    <h3 class="sidebar">Learning &amp; leadership</h3>
    <!--beginnoindex-->
    <ul id="nav2xc">

        <li class="xc"><a href="/hr/leadership/home.htm">Leadership</a>
            <ul id="Leadership">
                <li><a href="/hr/leadership/about.htm">About the Leadership Development Strategy</a></li>
                <li><a href="/hr/leadership/strategy.htm">Leadership Development Strategy</a></li>
                <li><a href="/hr/leadership/profiles.htm">Leader profiles</a></li>
                <li><a href="/hr/leadership/executives.htm">Executive program</a></li>
                <li><a href="/hr/leadership/leaders.htm">Leaders program</a></li>
                <li><a href="/hr/leadership/supervisors.htm">Supervisors program</a></li>
                <li><a href="/hr/learning/influencing-behaviours-for-success.htm">Influencing behaviours for success </a></li>
                <li><a href="/hr/leadership/resources.htm">Resources</a></li>
                <li><a href="/hr/leadership/reports.htm">Reports</a></li>
            </ul>
        </li>

        <!--endnoindex-->

        <li class="xc"><a href="/hr/mentoring/home.htm">Mentoring</a>
          <ul id="Mentoring">
            <li><a href="/hr/mentoring/vision.htm">Vision and objectives</a></li>
            <li><a href="/hr/mentoring/mentor-me/home.htm">MentorMe</a><br>
              <div>
                <a href="/hr/mentoring/be-a-mentor/about.htm">Be a mentor</a><br>
                <div>
                  <a href="/hr/mentoring/be-a-mentor/support-resources.htm">Support &amp; resources</a><br>
                  <a href="/hr/mentoring/be-a-mentor/FAQs.htm">FAQs</a><br>
                </div>
                <a href="/hr/mentoring/get-a-mentor/about.htm">Get a mentor</a><br>
                <div><a href="/hr/mentoring/get-a-mentor/support-resources.htm">Support &amp; resources</a><br>
                  <a href="/hr/mentoring/get-a-mentor/FAQs.htm">FAQs</a></div>
              </div>
            </li>
            <li><a href="/hr/mentoring/mentor-match/home.htm">MentorMatch</a></li>
          </ul>
        </li>

        <!--endnoindex-->

        <li class="xc"><a href="/hr/next-generation/home.htm">Next generation program</a></li>

        <!--endnoindex-->

        <li class="xc"><a href="/safety/elearning.htm">Online learning</a></li>

        <!--endnoindex-->

        <li class="xc"><a href="/hr/pdp/performance-dev-planning.htm">PDP</a></li>

        <!--endnoindex-->

        <li class="xc"><a href="/hr/learning/training-calendar.htm">Training calendar</a></li>

        <!--endnoindex-->

        <li class="xc"><a href="https://www.health.qld.gov.au/cunninghamcentre/default.asp">Training incentive funds</a></li>

        <!--endnoindex-->

        <li class="xc"><a href="/hr/womens-network/home.htm">Women's Network</a>
            <ul id="Womens Network">
                <li><a href="/hr/womens-network/steering-committee.htm">Women's Network Steering Committee</a></li>
            </ul>
        </li>

        <!--endnoindex-->

    </ul>
</div>
