<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Related links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fas fa-globe fa-lg" aria-hidden="true "></i><a href="#">External link</a></li>
            <li><i class="fa-li fas fa-link fa-lg" aria-hidden="true "></i><a href="#">Internal link</a></li>
        </ul>
    </div>
</div>
<!-- END Related links section -->
<!-- BEGIN Supporting resources section -->
<div class="sidebar_section">
    <h3 class="sidebar">Supporting resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fas fa-file-pdf fa-lg" aria-hidden="true"></i><a href="#">A PDF file that couldn't be a page</a> (PDF, XXXkB)</li>
            <li>
                <i class="fa-li fas fa-file-word fa-lg" aria-hidden="true"></i><a href="#">Word file (probably a form)</a> (DOC, XXXkB)</li>
        </ul>
    </div>
</div>
<!-- END Supporting resources section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <!-- Customise with section contact's direct email -->
                <i class="fa-li fas fa-envelope fa-lg" aria-hidden="true"></i><strong><a href="mailto:SectionContact@health.qld.gov.au">Email DeptName</a></strong>
            </li>
            <li><i class="fa-li fas fa-address-book fa-lg " aria-hidden="true "></i><a href="mailto:HRConnect@health.qld.gov.au">Email HR Connect</a></li>
        </ul>
    </div>
</div>
<!-- END Contact section -->