<div id="container">
    <ul id="nav">
        <li><a href="/hr/home.htm">HR home</a>
            <ul>
                <li><a href="/hr/about_us/home.htm">About HR Branch</a></li>
            </ul>
        </li>
        <li><a href="#" class="not-active">Workplace culture</a>
            <ul>
                <li><a href="/hr/culture/home.htm">Our culture</a></li>
                <li><a href="/hr/culture/sparks/home.htm">Spark network</a></li>
                <li><a href="/hr/diversity-inclusion/home.htm">Diversity inclusion and engagement</a></li>
                <li><a href="/hr/workplace-culture/working-for-queensland-survey/home.htm">Working for Queensland Survey</a></li>
                <li><a href="/hr/workplace-culture/code-of-conduct/home.htm">Code of conduct</a></li>
                <li><a href="/hr/employee-complaints/home.htm">Employee complaints</a></li>
            </ul>
        </li>
        <li><a href="#" class="not-active">Pay, leave &amp; benefits</a>
            <ul>
                <li><a href="/paris/">Payroll and rostering (PARIS)</a></li>
                <li><a href="/paris/forms/avac.htm">Attendance variations</a></li>
                <li><a href="/paris/employees/leave.htm">Applying for leave</a></li>
                <li><a href="/hr/pay-leave-benefits/wage-rates/home.htm">Wage rates</a></li>
                <li><a href="/streamline/">Payroll self service (Streamline)</a></li>
                <li><a href="/paris/employees/home.htm">Payroll processes for employees</a></li>
                <li><a href="/paris/managers/home.htm">Payroll processes for managers</a></li>
                <li><a href="/paris/reporting/home.htm">Roster management (Workbrain)</a></li>
                <li><a href="/hr/pay-leave-benefits/salary-packaging/home.htm">Salary packaging</a></li>
                <li><a href="/hr/pay-leave-benefits/superannuation/home.htm">Superannuation</a></li>
                <li><a href="/hr/staff-wellness/corporate-discounts/home.htm">Corporate discounts</a></li>
                <li><a href="/paris/calendar/home.htm">Calendars</a></li>
                <li><a href="/paris/glossary/home.htm">Glossary</a></li>
            </ul>
        </li>
        <li><a href="#" class="not-active">Policies, agreements &amp; directives</a>
            <ul>
                <li><a href="/hr/policies-agreements-directives/policy-index/home.htm">HR policy index</a></li>
                <li><a href="/hr/policies-agreements-directives/awards-agreements/home.htm">Awards &amp; agreements</a></li>
                <li><a href="/hr/employment-conditions/home.htm">Employment conditions</a></li>
                <li><a href="/peopleandculture/exec_policy/home.htm">Executive &amp; senior officer employment</a></li>
                <li><a href="/hr/policies-agreements-directives/enterprise-bargaining/home.htm">Enterprise bargaining</a></li>
                <li><a href="/hr/policies-agreements-directives/health-employment-directives/home.htm">Health employment directives</a></li>
                <li><a href="/hr/circulars/home.htm">HR circulars (updates)</a></li>
                <li><a href="/hr/policies-agreements-directives/psc-directives/home.htm">PSC & IR directives</a></li>
                <li><a href="/hr/policies-agreements-directives/delegations/home.htm">HR delegations manuals</a></li>
                <li><a href="/hr/pay-leave-benefits/smo-advancement/home.htm">Senior medical officer advancement</a></li>
                <li><a href="/hr/policies-agreements-directives/union-encouragement/home.htm">Union encouragement</a></li>
            </ul>
        </li>
        <li><a href="#" class="not-active">Workplace health &amp; safety</a>
            <ul>
                <li><a href="/safety/sms/home.htm">Safety management system</a></li>
                <li><a href="/safety/employees/emergencies.htm">Emergency management</a></li>
                <li><a href="/safety/employees/incident_reporting.htm">Reporting incidents</a></li>
                <li><a href="/safety/employees/first-aid.htm">First aid in the workplace</a></li>
                <li><a href="/safety/ergo/resources_office.htm">Workstation ergonomics</a></li>
                <li><a href="/safety/occup_violence/home.htm">Occupational Violence Prevention</a></li>
                <li><a href="/hr/html/health-safety.htm">OHS practitioners tools</a></li>
                <li><a href="/hr/crrr/home.htm">Community Recovery Ready Reserve</a></li>
            </ul>
        </li>
        <li><a href="#" class="not-active">Staff health &amp; wellbeing</a>
            <ul>
                <li><a href="/hr/staff-health-wellbeing/staff-wellbeing/home.htm">Staff wellbeing</a></li>
                <li><a href="/hr/staff-vaccinations/home.htm">Staff vaccinations</a></li>
                <li><a href="/hr/staff-health-wellbeing/domestic-family-violence/home.htm">Domestic and family violence</a></li>
                <li><a href="/hr/staff-health-wellbeing/domestic-family-violence/white-ribbon-accreditation.htm">White ribbon accreditation</a></li>
                <li><a href="/hr/staff-health-wellbeing/counselling-support/home.htm">Counselling and support</a></li>
            </ul>
        </li>
        <li><a href="#" class="not-active">Careers &amp; recruitment</a>
            <ul>
                <li><a href="/hr/recruitment/home.htm">Processes</a></li>
                <li><a href="/hr/policies-agreements-directives/executive-employment/recruitment/home.htm">Executive and senior officers</a></li>
                <li><a href="/hr/weg/">Job evaluation</a></li>
                <li><a href="/hr/weg/html/rdlibrary.htm">Role descriptions</a></li>
                <li><a href="/hr/visa-and-immigration/home.htm">Visa &amp; immigration</a></li>
                <li><a href="/hr/onboarding/home.htm">Onboarding</a></li>
                <li><a href="/hr/onboarding/orientation/home.htm">Orientation</a></li>
                <li><a href="/hr/erp/erp-home.htm">Employees requiring placement</a></li>
                <li><a href="https://www.health.qld.gov.au/employment">Work for us (internet)</a></li>
                <li><a href="https://www.health.qld.gov.au/employment/work-for-us/clinical/nursing-midwifery/graduate-campaigns">Graduate campaigns</a></li>
            </ul>
        </li>
        <li><a href="#" class="not-active">Training &amp; development</a>
            <ul>
                <li><a href="https://ilearncatalogue.health.qld.gov.au/">Online course catalogue</a></li>
                <li><a href="/hr/learning/training-calendar.htm">Training calendar</a></li>
                <li><a href="/hr/onboarding/mandatory.htm">Mandatory training</a></li>
                <li><a href="/ilearn/">Online learning (iLearn)</a></li>
                <li><a href="/hr/training-development/ceb/">CEB Corporate leadership council</a></li>
                <li><a href="/hr/training-development/performance/development/home.htm">Career success plans (CSP)</a></li>
                <li><a href="/hr/training-development/strategy/performance-capability-recognition/home.htm">Performance, Capability & Recognition</a></li>
                <li><a href="/hr/training-development/performance/management/home.htm">Performance reviews and discipline</a></li>
                <li><a href="/hr/mentoring/home.htm">Mentoring</a></li>
                <li><a href="/hr/next-generation/home.htm">Future leaders (Next generation)</a></li>
                <li><a href="/hr/leadership/home.htm">Leadership development</a></li>
                <li><a href="/hr/womens-network/home.htm">Womens Network</a></li>
            </ul>
        </li>
        <li><a href="#" class="not-active">Forms &amp; templates</a>
            <ul>
                <li><a href="/hr/recruitment/employment-screening/home.htm">Employment screening</a></li>
                <li><a href="/hr/online/home.htm">Online publishing</a></li>
                <li><a href="/paris/forms/home.htm">Payroll &amp; rostering forms (PARIS)</a></li>
                <li><a href="/hr/pdp/performance-dev-planning.htm">PDP &ndash; Performance and development</a></li>
                <li><a href="/hr/recruitment/start-recruiting/filling-a-vacancy.htm#role">Role descriptions</a></li>
            </ul>
        </li>
        <li><a href="#" class="not-active">Contacts</a>
            <ul>
                <li><a href="/hr/contacts/local-hr-units.htm">Local HR units</a></li>
                <li><a href="/hr/contacts/local-hr-units.htm#doh">Department of Health</a></li>
                <li><a href="/hr/contacts/eds-workforce.htm">Executive Directors Workforce</a></li>
                <li><a href="/hr/contacts/hrsbranch.htm">HR Branch</a></li>
                <li><a href="/hr/contacts/whs.htm">Workplace health &amp; safety </a></li>
            </ul>
        </li>
    </ul>
</div>