<div id="nav2">
    <!-- <a name="sidenav"></a>
    <h3 class="sidebar">Human Resources</h3>
    <!--beginnoindex-->
    <ul id="nav2xc">

        <li><a href="/hr/home.htm" title="Human Resources home">Home</a>

        </li>

        <!--endnoindex-->

        <li><a href="/hr/about_us/home.htm" title="About HR">About HR</a>

        </li>

        <!--endnoindex-->

        <li><a href="/hr/culture/home.htm" title="Workplace culture">Workplace culture</a>

            <ul id="Workplace culture">

                <li><a href="http://qheps.health.qld.gov.au/hr/culture/our-journey.htm" title="Our culture journey">Our culture journey</a></li>

                <li><a href="http://qheps.health.qld.gov.au/hr/culture/connectedness/home.htm" title="Connectedness">Connectedness</a></li>

                <li><a href="http://qheps.health.qld.gov.au/hr/culture/performance/home.htm" title="Performance">Performance</a></li>

                <li><a href="http://qheps.health.qld.gov.au/hr/culture/clarity/home.htm" title="Clarity">Clarity</a></li>

                <li><a href="http://qheps.health.qld.gov.au/hr/culture/respect/home.htm" title="Respect">Respect</a></li>

                <li><a href="http://qheps.health.qld.gov.au/hr/culture/capability/home.htm" title="Capability">Capability</a></li>

                <li><a href="http://qheps.health.qld.gov.au/hr/culture/sparks/home.htm" title="Sparks network">Sparks network</a></li>

            </ul>
        </li>

        <!--endnoindex-->

        <li><a href="/paris/employees/leave.htm">Pay, leave & benefits</a>

            <ul id="Pay leave & benefits">

                <li><a href="/hr/html/salaries-benefits.htm#payroll" title="Payroll assistance">Payroll assistance</a></li>

                <li><a href="/hr/html/salaries-benefits.htm#wage" title="Wage rates">Wage rates</a></li>

                <li><a href="/hr/html/salaries-benefits.htm#exec" title="Executive positions">Executive positions</a></li>

                <li><a href="/hr/html/salaries-benefits.htm#insurance" title="Health insurance">Health insurance</a></li>

                <li><a href="/hr/html/salaries-benefits.htm#mcontracts" title="Medical contracts">Medical contracts</a></li>

                <li><a href="/hr/html/salaries-benefits.htm#parental" title="Parental leave pay">Parental leave pay</a></li>

                <li><a href="/hr/html/salaries-benefits.htm#qsuper" title="QSuper">QSuper</a></li>

                <li><a href="/hr/html/salaries-benefits.htm#salary" title="Salary sacrificing">Salary packaging</a></li>

            </ul>
        </li>

        <!--endnoindex-->

        <li><a href="/hr/employment-conditions/home.htm" >Policies agreements and directives</a>

            <ul id="Policies agreements and directives">

                <li><a href="/hr/employment-conditions/policies-index.htm">Policy index</a></li>

                <li><a href="/hr/employment-conditions/home.htm#concern" title="Employee complaints">Employee complaints</a></li>

                <li><a href="/hr/employment-conditions/home.htm#eb" title="Enterprise Bargaining (EB)">Enterprise Bargaining (EB)</a></li>

                <li><a href="/hr/employment-conditions/home.htm#contracts" title="Employment contracts">Employment contracts</a></li>

                <li><a href="/hr/employment-conditions/home.htm#heds" title="Health employment directives">Directives</a></li>

                <li><a href="/hr/employment-conditions/home.htm#policies" title="HR Delegations">HR Delegations</a></li>

                <li><a href="/hr/employment-conditions/home.htm#policies" title="HR policies and circulars">HR policies and circulars</a></li>

                <li><a href="/hr/employment-conditions/home.htm#ir" title="HR delegations">Industrial relations</a></li>

                <li><a href="/hr/employment-conditions/home.htm#rates" title="Wage rates">Wage rates</a></li>

            </ul>
        </li>

        <!--endnoindex-->

        <li><a href="/hr/html/health-safety.htm" title="Workplace health & safety">Workplace health & safety</a>

            <ul id="Workplace health & safety">

                <li><a href="/hr/html/health-safety.htm" title="Your health & wellbeing">Your health & wellbeing</a></li>

                <li><a href="http://qheps.health.qld.gov.au/eap/" title="Employee assistance">Employee assistance program</a></li>

                <li><a href="http://qheps.health.qld.gov.au/eap/html/MgrAssist.htm" title="Manager assistance">Manager assistance</a></li>

                <li><a href="/hr/html/health-safety.htm" title="Reporting incidents">Reporting incidents</a></li>

                <li><a href="/hr/domestic-violence/home.htm" title="Domestic and family violence in the workplace">Domestic and family violence</a></li>

                <li><a href="http://qheps.health.qld.gov.au/safety/occup_violence/home.htm" title="Occupational Violence Prevention">Occupational Violence Prevention</a></li>

                <li><a href="/hr/html/health-safety.htm" title="News - changes to industry">News - changes to industry</a></li>

                <li><a href="/hr/html/health-safety.htm" title="OHS practitioners tools - safety management system">OHS practitioners tools</a></li>

                <li><a href="/hr/staff-vaccinations/home.htm" title="Staff flu vaccinations">Staff flu vaccinations</a></li>

                <li><a href="/hr/staff-wellness/home.htm" title="Staff wellness">Staff wellness</a></li>

                <li><a href="/hr/staff-wellness/week/home.htm" title="Safety and Wellness week 2016">Safety and Wellness week 2016</a></li>

            </ul>
        </li>

        <!--endnoindex-->

        <li><a href="/hr/html/ethics-conduct.htm" title="Ethics & conduct">Ethics & conduct</a>

            <ul id="Ethics & conduct">

                <li><a href="/hr/performance/home.htm" title="Behaviour & performance">Behaviour & performance</a></li>

                <li><a href="/hr/codeofconduct/home.htm" title="Code of conduct">Code of conduct</a></li>

                <li><a href="/hr/corrupt-conduct/home.htm" title="Corrupt conduct">Corrupt conduct</a></li>

                <li><a href="/hr/corrupt-conduct/criminal-matters.htm" title="Criminal matters">Criminal matters</a></li>

                <li><a href="/hr/employee-complaints/home.htm" title="Reporting concerns">Employee complaints</a></li>

                <li><a href="/hr/diversity-inclusion/home.htm" title="Diversity, inclusion and engagement">Diversity, inclusion and engagement</a></li>

                <li><a href="/hr/employee-complaints/home.htm" title="Harrassment">Harrassment</a></li>

                <li><a href="/hr/pid/home.htm" title="Public interest disclosure">Public interest disclosure</a></li>

            </ul>
        </li>

        <!--endnoindex-->

        <li><a href="/hr/html/careers-recruitment.htm" title="Careers & recruitment">Careers & recruitment</a>

            <ul id="Careers & recruitment">

                <li><a href="/hr/erp/erp-home.htm" title="Employees requiring placement (ERP)">Employees requiring placement (ERP)</a></li>

                <li><a href="https://www.health.qld.gov.au/employment/work-for-us/clinical/nursing-midwifery/graduate-campaigns/default.asp" title="Graduate recruitment">Graduate recruitment</a></li>

                <li><a href="/hr/weg/home.htm" title="Job evaluation">Job evaluation</a></li>

                <li><a href="/hr/er/html/mo3mo4-advancement.htm" title="MO3/MO4 advancement">MO3/MO4 advancement</a></li>

                <li><a href="/hr/recruitment/home.htm" title="Recruitment & selection">Recruitment & selection</a></li>

                <li><a href="/hr/onboarding/home.htm" title="Onboarding ">Onboarding </a></li>

                <li><a href="/hr/onboarding/orientation/home.htm" title="Orientation">Orientation</a></li>

                <li><a href="/hr/weg/html/rdlibrary.htm" title="Role descriptions">Role descriptions</a></li>

                <li><a href="/hr/visa-and-immigration/home.htm" title="Visas & immigration">Visa & immigration</a></li>

                <li><a href="https://www.health.qld.gov.au/employment/default.asp" title="Work for us">Work for us</a></li>

            </ul>
        </li>

        <!--endnoindex-->

        <li><a href="/hr/html/learning-leadership.htm" title="Learning & leadership">Learning & leadership</a>

            <ul id="Learning & leadership">

                <li><a href="/hr/leadership/profiles.htm" title="Leader profiles">Leader profiles</a></li>

                <li><a href="/hr/leadership/home.htm" title="Leadership development programs">Leadership development</a></li>

                <li><a href="/hr/mentoring/home.htm" title="Mentoring program">Mentoring program</a></li>

                <li><a href="/hr/next-generation/home.htm" title="Next generation program">Next generation program</a></li>

                <li><a href="http://qheps.health.qld.gov.au/safety/elearning.htm" title="Online learning">Online learning</a></li>

                <li><a href="/hr/pdp/performance-dev-planning.htm" title="Performance and development planning">PDP</a></li>

                <li><a href="/hr/learning/training-calendar.htm" title="Training calendar">Training calendar</a></li>

                <li><a href="https://www.health.qld.gov.au/cunninghamcentre/default.asp" title="Training incentive funds">Training incentive funds</a></li>

                <li><a href="/hr/womens-network/home.htm" title="Womens Network">Womens Network</a></li>

            </ul>
        </li>

        <!--endnoindex-->

        <li><a href="/hr/html/forms-templates.htm" title="Forms & templates">Forms & templates</a>

            <ul id="Forms & templates">

                <li><a href="/hr/recruitment/employment-screening/home.htm" title="Employment screening">Employment screening</a></li>

                <li><a href="/hr/online/home.htm" title="Online publishing for HR">Online publishing</a></li>

                <li><a href="http://qheps.health.qld.gov.au/paris/html/forms_home.htm" title="Payroll & rostering forms (PARIS)">Payroll & rostering forms (PARIS)</a></li>

                <li><a href="/hr/pdp/performance-dev-planning.htm" title="PDP - Performance and development">PDP - Performance and development</a></li>

                <li><a href="http://qheps.health.qld.gov.au/hr/recruitment/start-recruiting/filling-a-vacancy.htm#role" title="Role descriptions">Role descriptions</a></li>

            </ul>
        </li>

        <!--endnoindex-->

        <li><a href="/hr/html/contact.htm" title="Contact us">Contact us</a>

            <ul id="Contact us">

                <li><a href="/hr/contact/local-hr-contacts.htm" title="Your local HR unit">Your local HR unit</a></li>

                <li><a href="/hr/contact/hrsbranch.htm" title="HR Branch contacts">HR Branch contacts</a></li>

                <li><a href="/hr/contact/pace.htm" title="People and culture executive (PACE) ">People and culture executive (PACE) </a></li>

                <li><a href="/hr/contact/local-hr-contacts.htm#divhr" title="CSD">Corporate Services Division</a></li>

                <li><a href="/hr/contact/local-hr-contacts.htm#divhr" title="HSQ">Health Support Queensland</a></li>

                <li><a href="/hr/contact/local-hr-contacts.htm#hsia" title="eHealth Queensland">eHealth Queensland</a></li>

                <li><a href="/hr/contact/local-hr-contacts.htm#divhr" title="Office of the DG">Office of the DG</a></li>

                <li><a href="http://qheps.health.qld.gov.au/paris/contact/home.htm" title="Local payroll service centres">Local payroll service centres</a></li>

                <li><a href="http://qheps.health.qld.gov.au/hr/recruitforfit/contact/home.htm" title="Recruitment contacts">Recruitment contacts</a></li>

                <li><a href="http://qheps.health.qld.gov.au/safety/communications/contact_us2.htm" title="Workplace health & safety">Workplace health & safety</a></li>

            </ul>
        </li>

        <!--endnoindex

    </ul> -->
</div>
