<div class="sidebar_section">
    <h3 class="sidebar">Search HR</h3>
    <div class="hr-form hr-search">
        <script type="text/javascript" src="http://qheps.health.qld.gov.au/_includes/scripts/funnelback.js"></script>
        <form action="javascript: fbsearch('s-search','qheps.health.qld.gov.au/hr,qheps.health.qld.gov.au/eap,qheps.health.qld.gov.au/ilearn,qheps.health.qld.gov.au/paris,qheps.health.qld.gov.au/safety');" name="s-search">
            <input name="query" class="query" size="25" type="text" placeholder="Type search terms + enter" />
            <input id="searchbut" type="submit" value="" />
        </form>
    </div>
</div>