<div id="rightcolumn">

  <div class="hr-logo"><img src="/hr/images/Human-Resources-logo.png" alt="Human Resources Department of Health" /></div>

  <!-- #include virtual="/hr/include/master-search.inc" -->
  <!-- #include virtual="/hr/include/master-quick_links.inc" -->
  <div class="opm-logo"><img src="/hr/images/Our-People-Matter_logo.png" alt="Our people matter" width=170></div>
</div>
