<!-- BEGIN Contact section -->
<div class="sidebar_section">
  <h3 class="sidebar">Need more help?</h3>
  <div class="quick_links">
    <ul class="fa-ul">
      <li>
        <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><strong><a href="mailto:HRConnect@health.qld.gov.au">email HR Connect</a></strong>
        <!-- Customise with sub-site contact's direct email -->
      </li>
      <li>
        <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="/hr/contacts/local-hr-units.htm">Contact your local HR</a></strong>
      </li>
    </ul>
  </div>
</div>
<!-- END Contact section -->
