<div id="nav2">
    <a name="sidenav"></a>
    <h3 class="sidebar">Pay, leave &amp; benefits</h3>
    <!--beginnoindex-->
    <ul id="nav2xc">
        <li><a href="/paris">PARIS home</a></li>
        <!--endnoindex-->
        <li><a href="/paris/forms/avac.htm">Attendance variations</a></li>
        <!--endnoindex-->
        <li><a href="/paris/employees/leave.htm">Applying for leave</a></li>
        <!--endnoindex-->
        <li><a href="/hr/pay-leave-benefits/wage-rates/home.htm">Wage rates</a></li>
        <!--endnoindex-->
        <li><a href="/paris/employees/home.htm">Payroll processes for employees</a>
            <ul id="Payroll processes for employees">
                <li><a href="/paris/employees/leave.htm">Leave</a></li>
                <li><a href="/paris/employees/pay-advance.htm">Pay in advance</a></li>
                <li><a href="/paris/employees/personal.htm">Personal information</a></li>
                <li><a href="/paris/employees/work-arrangements.htm">Work arrangements</a></li>
                <li><a href="/paris/employees/allowances.htm">Allowances &amp; deductions</a></li>
                <li><a href="/paris/employees/separate.htm">Separation</a></li>
                <li><a href="/paris/employees/education.htm">Education/professional development</a></li>
                <li><a href="/paris/employees/concurrent.htm">Concurrent employment</a></li>
                <li><a href="/paris/employees/vmo-callback.htm">VMO call back</a></li>
                <li><a href="/paris/employees/validate-claim.htm">Validate old claims</a></li>
                <li><a href="/paris/employees/financial-hardship.htm">Alternative repayments</a></li>
                <li><a href="/paris/managers/payslip-messages.htm">Payslip messages</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li><a href="/paris/managers/home.htm">Payroll processes for managers</a>
            <ul id="Payroll processes for managers">
                <li><a href="/paris/managers/work-unit.htm">Manage employees</a></li>
                <li><a href="/paris/managers/team-roster.htm">Work team roster</a></li>
                <li><a href="/paris/managers/establishment.htm">Work unit establishment</a></li>
                <li><a href="/paris/managers/costing.htm">Costing</a></li>
                <li><a href="/paris/managers/grandparent.htm">Grandparent clause</a></li>
                <li><a href="/paris/managers/casual.htm">Casual to non-casual</a></li>
                <li><a href="/paris/managers/concurrent.htm">Concurrent employees</a></li>
                <li><a href="/paris/managers/overtime-district.htm">Overtime payments (District)</a></li>
                <li><a href="/paris/managers/payslip-messages.htm">Payslip messages</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li><a href="/paris/reporting/home.htm">Roster management (Workbrain)</a>
            <ul id="Roster management">
                <li><a href="/paris/reporting/the-basics.htm">Workbrain basics</a></li>
                <li><a href="/paris/reporting/edit-access.htm">Workbrain edit access</a></li>
                <li><a href="/paris/reporting/reports.htm">Reports</a></li>
                <li><a href="/paris/reporting/support-docs.htm">Support documents</a></li>
                <li><a href="/paris/reporting/contacts.htm">Workforce management contacts</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li><a href="/hr/pay-leave-benefits/salary-packaging/home.htm">Salary packaging</a></li>
        <!--endnoindex-->
        <li><a href="/hr/pay-leave-benefits/superannuation/home.htm">Superannuation</a></li>
        <!--endnoindex-->
        <li><a href="/hr/staff-health-wellbeing/staff-wellbeing/financial-wellbeing/corporate-discounts.htm">Corporate discounts</a></li>
        <!--endnoindex-->
        <li><a href="/paris/calendar/home.htm" title="Payroll calendars">Calendars</a>
        </li>
        <!--endnoindex-->
        <li><a href="/paris/glossary/home.htm" title="Glossary">Glossary</a>
        </li>
        <!--endnoindex-->
        <li></li>
        <!--blank spacer. needed as QHEPS shell table styles conflict with custom styles here -->
    </ul>
</div>