<div id="rightcolumn">
    <div class="hr-logo"><img src="/hr/images/human-resources-logo.png" alt="Human Resources Department of Health" /></div>
    <!--#include virtual="/hr/include/master-search.inc" -->
    <!--#include virtual="/SectionFolderName/includes/quick_links-sectionName.inc" -->
    <!-- #include virtual="/hr/include/aside-feedback.inc" -->
    <div class="opm-logo"><img src="/hr/images/our-people-matter_logo.png" alt="Our people matter" width=170></div>
</div>