<style>
h1 {clear: both;color:#69C1ED; padding:0; margin: 5px 0; line-height: 120%; font-size: 30px; letter-spacing: -1px;border: 0px;}
h2 {clear: both;color:#0076BD; padding:0; margin: 10px 0; line-height: 120%;border: 0px;}
h3 {clear: both; margin: 5px 0; color: #0D4E95; line-height: 120%;border: 0px;}
h4 {clear: both; margin: 5px 0; color: #999; line-height: 120%;border: 0px;}
#nav li ul li {width: 200px;}
#nav li ul li:hover {width: 200px;}
#nav2 #nav2xc {padding: 10px 0 0 30px;}
#pagepadMain.content {background: url(/hr/images/background/block70_bg.jpg) 10px 30px no-repeat;}
#pagepadMain.content #contentblock70 {padding:0 0 0 40px;}
#contentblock30{border: 0px;}
#footer {border:0;}
hr{border: 0px; border-top: 1px solid #d4cabe;}
img{border: 0px;}
#contentblock30 input.greenbtn{background: #fff;}
#contentblock30 form input{background: #ededed; border: 1px solid #ccc;}

</style>
