<!--[if IE 6]><style type="text/css">.pac_content_table {
    margin: 0 0 0 30px;
}

</style><![endif]-->

<style type="text/css">

#nav li ul li {
    width: 200px;
}

#nav li ul li:hover {
    width: 200px;
}

#nav2 #nav2xc {
    padding: 10px 0 0 30px;
}

#pagepadMain.content {
    background: url(/hr/images/background/block70_bg.jpg) 10px 30px no-repeat;
}

#pagepadMain.content #contentblock70 {
    padding: 0 0 0 40px;
}

#hrs_right_column_shadow {
    padding: 90px 0 0 30px;
    margin: 0;
    background: url(/hr/images/background/block30_bg.jpg) top left no-repeat;
    float: right;
    border: 0;
    text-align: left;
    min-height: 430px;
}

#hrc_right_column_shadow {
    padding: 90px 0 0 30px;
    margin: 0;
    background: url(/hr/images/background/block30hrc_bg.jpg) top left no-repeat;
    float: right;
    border: 0;
    text-align: left;
    min-height: 430px;
}

#contentblock30 {
    border: 0px;
}

html>body #contentblock70 {
    width: 64%
}

#rightcolumn {
    width: 100%;
    margin: 0 0 10px 0;
}

#contentblock70 p {
    padding: 0;
    margin: 10px 0;
}

#footer {
    border: 0;
}

#footer_top {
    z-index: 10;
    height: 117px;
    border: 0;
    width: 1024px;
    clear: both;
    background: url(/hr/images/background/bottombg.gif) top no-repeat;
}

#footer_wrap {
    height: 117px;
    border: 0;
    width: 100%;
    clear: both;
    background: url(/hr/images/background/bottombgwrap.gif) top repeat-x;
}

#side_ads {
    position: absolute;
    left: 25px;
    top: 420px;
    height: 200px;
    width: 152px;
    display: block;
    z-index: 999;
}

#side_ad_2 {
    height: 79px;
    width: 152px;
    display: block;
    margin: 20px 0;
}

#side_ad_1 {
    height: 79px;
    width: 152px;
    display: block;
    margin: 10px 0;
}

hr {
    border: 0px;
    border-top: 1px solid #d4cabe;
}

img {
    border: 0px;
}

img.float_left {
    float: left;
    margin: 0 10px 5px 0;
}

a.readmore {
    float: right;
    clear: both;
    display: block;
    width: 75px;
    text-align: center;
    background: #afcc99;
    padding: 3px 5px;
    color: #000;
    font-size: 11px;
    font-weight: bold;
    -moz-border-radius: 5px;
}

h1 {
    clear: both;
    color: #69C1ED;
    padding: 0;
    margin: 5px 0;
    line-height: 120%;
    font-size: 30px;
    letter-spacing: -1px;
    border: 0px;
}

h2 {
    clear: both;
    color: #0076BD;
    padding: 0;
    margin: 10px 0;
    line-height: 120%;
    border: 0px;
}

h3 {
    clear: both;
    margin: 5px 0;
    color: #0D4E95;
    line-height: 120%;
    border: 0px;
}

h4 {
    clear: both;
    margin: 5px 0;
    color: #999;
    line-height: 120%;
    border: 0px;
}

#rightcolumn h3 {
    display: table;
    width: 100%;
    color: #406463;
    margin: 0 0 5px 0;
    font-size: 18px;
    letter-spacing: -0.5px;
    padding: 0 0 0 20px;
}

#rightcolumn h3.search {
    background: url(/hr/images/list_icons/h3_search.gif) left no-repeat;
}

#rightcolumn h3.welcome {
    background: url(/hr/images/list_icons/h3_search.gif) left no-repeat;
}

#rightcolumn h3.shortcuts {
    background: url(/hr/images/list_icons/h3_shortcuts.gif) left no-repeat;
}

#rightcolumn h3.news {
    background: url(/hr/images/list_icons/h3_news.gif) left no-repeat;
}

#rightcolumn h3.feedback {
    background: url(/hr/images/list_icons/h3_feedback.gif) left no-repeat;
}

#rightcolumn p.welcome {
    color: #666;
    font-size: 11px;
    margin: 0 0 10px 0;
}

#hrs_right_column_shadow #feedback {
    background: url(/hr/images/right_column/feedback_icon.gif) top left no-repeat 20;
    padding: 0 0 0 45px;
}

h4 {
    padding: 10px 0px;
    color: #94918d;
    margin: 5px 0;
    line-height: 110%;
}

h5 {
    color: #94918d;
    padding: 0;
    margin: 5px 0;
    line-height: 110%;
    padding: 0 0;
}

h6 {
    padding: 0;
    margin: 5px 0;
    line-height: 110%;
}

#rightcolumn input.greenbtn {
    background: #fff;
}

#rightcolumn form input {
    background: #ededed;
    border: 1px solid #ccc;
    margin-bottom: 5px;
}

#rightcolumn .small {
    font-size: 11px;
}

.hrs_forms input {
    width: 250px;
}

.hrs_forms .hrs_textarea input {
    width: 350px;
    height: 100px;
}

#form_wrapper {
    background: url(/hr/images/contact_page/contact-bg.gif) left no-repeat;
    padding: 0 0 0 70px;
    height: 450px;
}


/* TODO: Can only be one ID per page. update all #quick_links to .quick_links_section */

#quick_links {
    margin: 15px 0;
}

#quick_links ul {
    margin: 0 10px 0 10px;
    padding: 0;
}

#quick_links li {
    list-style: none;
    border-bottom: 1px solid #ededed;
}

#quick_links li a {
    color: #0076BD;
    font-size: 12px;
    font-weight: bold;
    height: 20px;
    width: 100%;
    line-height: 150%;
    display: block;
    margin: 6px 0;
    padding: 2px 0 2px 30px;
}

#quick_links li a:hover {
    color: #83B965;
}


/* TODO (Jason): create new icons as per HR home rightcolumn and link here */

li.icon_bullet {
    background: #fff url(/hr/images/quick_links/icon-bullet.png) left no-repeat;
}

li.icon_link {
    background: #fff url(/hr/images/quick_links/icon-link.png) left no-repeat;
}

li.icon_calendar {
    background: #fff url(/hr/images/quick_links/icon-calendar.png) left no-repeat;
}

li.icon_comment {
    background: #fff url(/hr/images/quick_links/icon-comment.png) left no-repeat;
}

li.icon_contacts {
    background: #fff url(/hr/images/quick_links/icon-contacts.png) left no-repeat;
}

li.icon_email {
    background: #fff url(/hr/images/quick_links/icon-envelope.png) left no-repeat;
}


/* Deprecate once all rightcolumns are using specific icon references as above */

#quick_links li.item1 {
    background: #fff url(/hr/images/quick_links/1.gif) left no-repeat;
}

#quick_links li.item2 {
    background: #fff url(/hr/images/quick_links/2.gif) left no-repeat;
}

#quick_links li.item3 {
    background: #fff url(/hr/images/quick_links/3.gif) left no-repeat;
}

#quick_links li.item4 {
    background: #fff url(/hr/images/quick_links/4.gif) left no-repeat;
}

#quick_links li.item5 {
    background: #fff url(/hr/images/quick_links/5.gif) left no-repeat;
}

#quick_links li.item6 {
    background: #fff url(/hr/images/quick_links/6.gif) left no-repeat;
}

#quick_links li.item7 {
    background: #fff url(/hr/images/quick_links/7.gif) left no-repeat;
}

.front_box_tr {
    clear: both;
    width: 100%;
}

.front_box_bg {
    display: block;
    width: 210px;
    height: 98px;
    background: url(/hr/images/front_box/front_box_bg.gif) bottom left no-repeat;
    position: relative;
    float: left;
}

.front_box_image {
    position: absolute;
    top: 37px;
    left: 15px;
}

img.front_box_image {
    border: 1px solid #999;
}

h3.front_box_bullet {
    display: block;
    width: 100%;
    height: 18px;
    position: absolute;
    top: 0px;
    left: 5px;
    font-size: 13px;
    padding: 0 0 0 15px;
    color: #6591c8;
    background: url(/hr/images/front_box/front_box_bullet.gif)left no-repeat;
}

.front_box_bullet a:link, .front_box_bullet a:visited {
    color: #406463;
}

#front_box_links {
    position: absolute;
    top: 30px;
    left: 75px;
    width: 125px;
    color: #666;
}

#front_box_links p {
    font-size: 10px;
}

#front_box_links a {
    font-size: 10px;
    color: #3399cc;
    text-decoration: none;
}

#front_box_links a:hover {
    text-decoration: underline;
}

p.more-info-hook a .section-heading {
    display: block;
    padding: 2px 0 2px 20px;
    margin: 0;
    text-decoration: none;
    background: url(/hr/images/quick_links/down_arrow.gif) left no-repeat;
}

p.more-info-hook a {
    text-decoration: none;
    font-weight: bold;
}

ul.resources {
    margin: 0;
    padding: 0;
}

.resources li {
    list-style: disc;
    margin: 0 0 0 15px;
    padding: 0;
    color: #999;
}

.resources li a {
    padding: 0;
    margin: 2px 0;
}

.entry_slider_left, .entry_slider_right {
    width: 250px;
    padding: 5px;
}

.entry_slider_left .more-information, .entry_slider_right .more-information {
    background: #ededed;
    border: 1px solid #ccc;
}

.entry_slider_left .resources li a {
    display: block;
    padding: 2px 4px;
    margin: 2px 0;
    text-decoration: none;
    border: 1px solid #ddd;
    background: #fafafa;
    text-align: center;
}

.entry_slider_right .resources li a {
    display: block;
    padding: 2px 4px;
    margin: 2px 0;
    text-decoration: none;
    border: 1px solid #ddd;
    background: #fafafa;
    text-align: center;
}

#entry_slider .section-heading {
    font-size: 14px;
    color: #2986a3;
}

</style>
