<tr><td>
<h3 class="shortcuts">Popular resources</h3>
</td></tr>

<tr><td>

<div id="quick_links">
<ul class="quick_links">
<li class="item1"><a href="http://qheps.health.qld.gov.au/hr/learning/training-calendar.htm">Training calendar</a></li>
<li class="item2"><a href="http://qheps.health.qld.gov.au/paris/forms/home.htm">Payroll forms</a></li>
<li class="item3"><a href="http://qheps.health.qld.gov.au/safety/home.htm">Safety & Wellbeing</a></li>
<li class="item4"><a href="http://qheps.health.qld.gov.au/hr/recruitment/">Recruitment</a></li>
<li class="item5"><a href="http://qheps.health.qld.gov.au/hr/employment-conditions/home.htm">Employment conditions</a></li>
<li class="item6"><a href="http://qheps.health.qld.gov.au/payroll-assistance/">Payroll assistance</a></li>
</ul>
</div>


</td></tr>
