<div id="nav2"><a name="sidenav"></a>
    <h3 class="sidebar">In this section</h3>
<!--beginnoindex-->
  <ul id="nav2xc">

        <li><a href="/hr/recruitment/home.htm">Recruitment</a>

	  </li>

<!--endnoindex-->

        <li><a href="/hr/recruitment/start-recruiting/home.htm">Start recruiting</a>

				<ul id="Start recruiting">

				<li><a href="/hr/recruitment/start-recruiting/filling-a-vacancy.htm">Filling a vacancy</a></li>
                </ul></li>

<!--endnoindex-->

		<li><a href="/hr/recruitment/job-evaluation">Job evaluation</a>
                <ul id="Job evaluation">
                <li><a href="">Executives</a></li>
                <li><a href="">General</a></li>
                <li><a href="/hr/recruitment/job-evaluation/health-practitioners/home.htm">Health practitioners</a><br>
                <div>
                <a href="/hr/recruitment/job-evaluation/health-practitioners/become-an-evaluator.htm">Become a HP evaluator</a><br>
                <a href="/hr/recruitment/job-evaluation/health-practitioners/request-an-evaluation.htm">Request a HP evaluation</a><br>
                <a href="/hr/recruitment/job-evaluation/health-practitioners/hp-evaluators-network.htm">HP Evaluators contact/network</a><br>
                <a href="/hr/recruitment/job-evaluation/health-practitioners/hp-evaluator-training.htm">HP Evaluator training</a>
                </div>
                </li>
                <li><a href="">Nursing</a></li>
                <li><a href="/hr/weg/html/vader.htm">VADER</a></li>
                </ul></li>

<!--endnoindex-->

				<li><a href="/hr/recruitment/start-recruiting/selection.htm">Selection</a></li>

<!--endnoindex-->

				<li><a href="/hr/recruitment/start-recruiting/pre-appointment.htm">Pre-appointment</a></li>

<!--endnoindex-->

				<li><a href="/hr/recruitment/start-recruiting/appointment.htm">Appointment</a></li>

<!--endnoindex-->

				<li><a href="/hr/recruitment/start-recruiting/orientation-induction.htm">Orientation and induction</a></li>

<!--endnoindex-->

        <li><a href="/hr/recruitment/employment-screening/home.htm">Employment screening</a>

				<ul id="Employment screening">

				<li><a href="/hr/recruitment/employment-screening/mandatory-vaccinations.htm">Mandatory vaccinations</a></li>

				<li><a href="/hr/recruitment/employment-screening/criminal-history-checks.htm">Criminal history</a></li>

				<li><a href="/hr/recruitment/employment-screening/blue-card.htm">Blue card</a></li>

				<li><a href="/hr/visa-and-immigration/home.htm">Visa and immigration</a></li>

			  </ul></li>

<!--endnoindex-->

        <li><a href="/hr/recruitment/systems/home.htm">Recruitment systems</a></li>

<!--endnoindex-->

        <li><a href="/hr/recruitment/rapid-fill-register/home.htm">Rapid fill register</a></li>

<!--endnoindex-->

        <li><a href="/hr/recruitment/policies.htm">Policies (A to Z)</a></li>

<!--endnoindex-->

        <li><a href="/hr/recruitment/forms.htm">All forms (A to Z)</a></li>

<!--endnoindex-->

        <li><a href="http://www.health.qld.gov.au/employment/job-search/hhs-recruitment-contact/default.asp">Contacts</a></li>

<!--endnoindex-->

        <li></li> <!--blank spacer. needed as QHEPS shell table styles conflict with custom styles here -->

  </ul>
</div>
