<!-- The search section differs in text surrounding the search compared to /hr/home.
TODO: This should be standardised across all pages at some point. -->
<div>
<h3 class="search">Search</h3>
</div>
<div>
  <p>This search is limited to&nbsp;HR pages only.</p>
<script type="text/javascript" src="http://qheps.health.qld.gov.au/_includes/scripts/funnelback.js"></script>
<form action="javascript: fbsearch('s-search','qheps.health.qld.gov.au/hr');" name="s-search"><input name="query" size="25" type="text" /> <input id="submitbut" type="submit" value=" Go " /> </form>
</div>
