<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Related Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="http://qheps.health.qld.gov.au/comms/awlsummit/home.htm">Aspiring Women Leaders' Summit 2017</a> (videos)</li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="http://qheps.health.qld.gov.au/comms/awlsummit/html/awlsummit-2016.htm">Aspiring Women Leaders' Summit 2016</a> (videos)</li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="http://qheps.health.qld.gov.au/comms/awlsummit/html/awlsummit-2015.htm">Aspiring Women Leaders' Summit 2015</a> (videos)</li>
        </ul>
    </div>
</div>
<!-- END Related Links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="mailto:womensnetwork@health.qld.gov.au">Email the Women's Network<a/></strong>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->