<style type="text/css">
#nav,
#nav ul {
    background: #44867c;
}

#nav li,
#nav li ul li {
    background: #44867c;
}

#nav li:hover,
#nav li.qhhover,
#nav li ul li:hover {
    background: #076a16;
}

h2 {
    color: #076a16;
    background: #c5dfe0;
}

h3 {
    color: #076a16;
}

h3.sidebar {
    background: #44867c;
}

.hr-form {
    background: #c5dfe0;
}

.hr-search #searchbut {
    background: url(/purchasing-performance/images/icon-search-greenbg.png) top no-repeat;
}

.hr-search #searchbut:hover {
    background: url(/purchasing-performance/images/icon-search-greenbg_hover.png) top no-repeat;
}








/*## HPSP colours */

.text-hpsp-green,
a.text-hpsp-green {
    color: #076a16;
}

.bg-hpsp-green {
    background-color: #076a16;
}
</style>