<div id="nav2">
    <a name="sidenav"></a>
    <h3 class="sidebar">Campaigns</h3>
    <!--beginnoindex-->
    <ul id="nav2xc">
        <li><a href="/hr/campaigns/safe-work-month/home.htm">Safe Work Month 2017</a>
            <ul id="Safe Work Month">
                <li><a href="/hr/campaigns/safe-work-month/whats-on.htm">What's on</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li></li>
        <!--blank spacer. needed as QHEPS shell table styles conflict with custom styles here -->
    </ul>
</div>