<div id="nav2">
    <a name="sidenav"></a>
    <h3 class="sidebar">In this section</h3>
    <!--beginnoindex-->
    <ul id="nav2xc">
        <!--
        <li><a href="/hr/contacts/home.htm">Contacts</a>
        </li> -->

        <!--endnoindex-->

        <li><a href="/hr/contacts/local-hr-units.htm">Local HR units</a>
        </li>

        <!--endnoindex-->

        <li><a href="/hr/contacts/local-hr-units.htm#doh">Department of Health</a>
        </li>

        <!--endnoindex-->

        <li><a href="/hr/contacts/eds-workforce.htm">Executive Directors Workforce</a>
        </li>

        <!--endnoindex-->

        <li><a href="/hr/contacts/hrsbranch.htm">HR Branch</a>
        </li>

        <!--endnoindex-->

        <li><a href="/hr/contacts/whs.htm">Workplace health and safety</a>
            <ul id="WHS">
                <li><a href="/hr/contacts/whs.htm#operational">Operational contacts</a></li>
                <li><a href="/hr/contacts/whs.htm#strategic">Strategic Safety &amp; Wellbeing Advisors</a></li>
            </ul>
        </li>

        <!--endnoindex-->

        <li></li> <!--blank spacer. needed as QHEPS shell table styles conflict with custom styles here -->

    </ul>
</div>
