<div id="nav2">
  <a name="sidenav"></a>
  <h3 class="sidebar">Ethics and conduct</h3>
      <!--beginnoindex-->
  <ul id="nav2xc">

    <li><a href="/hr/training-development/performance/management/home.htm">Behaviour &amp; performance</a></li>

    <!--endnoindex-->

    <li><a href="/hr/workplace-culture/code-of-conduct/home.htm">Code of conduct</a></li>

    <!--endnoindex-->

    <li><a href="/hr/corrupt-conduct/home.htm">Corrupt conduct</a></li>

    <!--endnoindex-->

    <li><a href="/hr/corrupt-conduct/criminal-matters.htm">Criminal matters</a></li>

    <!--endnoindex-->

    <li><a href="/hr/pid/home.htm">Public interest disclosures</a></li>

    <!--endnoindex-->

  </ul>
</div>
