<div id="nav2">
    <h3 class="sidebar">Forms &amp; templates</h3>
    <a name="sidenav"></a>
        <!--beginnoindex-->
        <ul id="nav2xc">

            <li><a href="/hr/recruitment/employment-screening">Employment screening</a></li>

            <!--endnoindex-->

            <li><a href="/hr/online">Online publishing</a>
              <ul id="Online publishing">
                <li><a href="/hr/online/html/approvals.htm">Publishing approval process</a></li>
                <li><a href="/hr/online/docs/hrs_online_pub_form.pdf">Publishing approval form</a></li>
                <li><a href="/oim/governance/home.htm">Policy and Standards</a></li>
                <li><a href="/oim/help/statistics/home.htm">Website statistics</a></li>
                <li><a href="/oim/help/home.htm">Publisher help and advice</a></li>
              </ul>
            </li>

            <!--endnoindex-->

            <li><a href="/paris/html/forms_home.htm">Payroll &amp; rostering forms (PARIS)</a></li>

            <!--endnoindex-->

            <li><a href="/hr/pdp/performance-dev-planning.htm">PDP &ndash; Performance and development</a></li>

            <!--endnoindex-->

            <li><a href="/hr/recruitment/start-recruiting/filling-a-vacancy.htm#role">Role descriptions</a></li>

            <!--endnoindex-->

            <li></li> <!--blank spacer. needed as QHEPS shell table styles conflict with custom styles here -->

        </ul>
</div>
