<ul class="bxslider">
    <!--min 3-max 5 at any one time. FILLERS indicated.-->
    <!-- C1 WfQ survey extended 28 August
    <li>
        <a href="/hr/workplace-culture/working-for-queensland-survey/home.htm">
            <img src="/hr/images/home-slider/2017-08-21_W4Q.jpg" alt="Working for Queensland survey, Survey extended" /></a>
        <p class="title">Survey extended - closes midnight 28 August - take the opportunity!</p>
        <p>Last chance to have your say - take the <a href="/hr/workplace-culture/working-for-queensland-survey/home.htm">survey</a> now.</p>
    </li>-->
    <!-- F1 Diversity and inclusion
    <li>
        <a href="/hr/diversity-inclusion/home.htm">
            <img src="/hr/images/home-slider/2017-07-27_DIE.jpg" alt="Diversity, inclusion and engagement" /></a>
        <p class="title">Everyone has a role to play.</p>
        <p><a href="/hr/diversity-inclusion/home.htm"> Do you know your role and responsibilities</a>?</p>
    </li>-->
    <!-- F13 LGBTIQ+ -->
    <!--<li>
        <a href="http://qheps.health.qld.gov.au/hr/diversity-inclusion/home.htm">
            <img src="/hr/images/home-slider/2017-08-31_LGBTIQ.jpg" alt="Lesbian, Gay, Bisexual, Transgender, Intersex, Queers" /></a>
        <p class="title">Diversity is key to a strong workplace.</p>
        <p>Inclusion starts with us.<a href="http://qheps.health.qld.gov.au/hr/diversity-inclusion/home.htm">Read more. </a></p>
    </li>-->
    <!--  C5 LGBTIQ+ Brisbane Pride Festival March -->
    <!--     <li>
        <a href="http://qheps.health.qld.gov.au/hr/diversity-inclusion/whats-on.htm">
            <img src="/hr/images/home-slider/2017-08-31_pride_march.jpg" alt="Brisbane's Pride Festival, September 2017" /></a>
        <p class="title">Celebrate and support your colleagues.</p>
        <p>Join the march 23 September. <a href="http://qheps.health.qld.gov.au/hr/diversity-inclusion/whats-on.htm">Register now.</a></p>
    </li> -->
    <!--  C6 Safe Work Month 2017
    <li>
        <a href="/hr/campaigns/safe-work-month/home.htm">
            <img src="/hr/images/home-slider/2017-10-09_safe-work-month.jpg" alt="Safe Work Month October 2017. Work safe for the moments that matter." /></a>
        <p class="title">Work safe for the moments that matter.</p>
        <p><a href="/hr/campaigns/safe-work-month/home.htm">Creating safe, secure and supportive workplaces</a>.</p>
        </li-->-->
    <!-- F5 Training Calendar-->
    <li>
        <a href="/hr/learning/training-calendar.htm">
            <img src="/hr/images/home-slider/2017-06-30_TC.jpg" alt="Training calendar, your opportunity to grow" /></a>
        <p class="title">November is packed with opportunities for everyone.</p>
        <p><a href="/hr/learning/training-calendar.htm">Book now</a>!</p>
    </li>
    <!-- F7 EAP Counselling and Support-->
    <li>
        <a href="/hr/staff-health-wellbeing/counselling-support/home.htm"><img src="/hr/images/home-slider/2017-06-30_EAP.jpg" alt="Employee Assistance. Our purpose is our people. Our focus is you." /></a>
        <p class="title">Employee assistance is available for you.</p>
        <p><a href="/hr/staff-health-wellbeing/counselling-support/home.htm">Learn more</a> about the services available.</p>
    </li>-->
    <!-- F8 Salary Sacrifice-->
    <li>
        <a href="/hr/pay-leave-benefits/salary-packaging/home.htm"><img src="/hr/images/home-slider/2017-10-07_bus-benefits.jpg" alt="New bus travel benefits" /></a>
        <p class="title">Are you eligible to salary sacrifice?</p>
        <p><a href="/hr/pay-leave-benefits/salary-packaging/home.htm">Check out the FAQs</a>.</p>
    </li>
    <!--F9 Peter Clarity-->
    <!-- <li>
    <a href="/hr/culture/clarity/home.htm#pete"><img src="/hr/images/home-slider/2017-08-11_ClarityPete.jpg" alt="Clarity. A foundation of our culture. Imperative to delivering our vision." /></a>
    <p class="title">Essential to delivering our vision.</p>
    <p><a href="/hr/culture/clarity/home.htm#pete">Watch Pete</a> achieve the clarity he needs.</p>
</li> -->
    <!-- F6 Performance Pete -->
    <!--<li>
        <a href="/hr/culture/performance/home.htm#pete"><img src="/hr/images/home-slider/2017-06-30_perfPete.jpg" alt="Performance Pete" /></a>
        <p class="title">Building a culture that is vibrant, innovative and collaborative.</p>
        <p>Hear Pete talk about performance <a href="/hr/culture/performance/home.htm#pete">watch now</a>.</p>
    </li>-->
    <!-- F4 DFV Domestic and Family Violence -->
    <!--<li>
        <a href="/hr/staff-health-wellbeing/domestic-family-violence/supporting-someone.htm"><img src="/hr/images/home-slider/2017-05-25_DFV.jpg" alt="Our department supports people affected by Domestic and Family Violence" /></a>
        <p class="title">Domestic and Family Violence is a workplace issue</p>
        <p><a href="/hr/staff-health-wellbeing/domestic-family-violence/supporting-someone.htm">Check out</a> what support is available.</p>
    </li>-->
    <!-- F2 CSP Career Success Planning -->
    <li>
        <a href="/hr/training-development/performance/development/home.htm"><img src="/hr/images/home-slider/2017-06-06_CSP.jpg" alt="Career success plan" /></a>
        <p class="title">Regular conversations are key</p>
        <p>Are you ready for your 6 month review? <a href="/hr/training-development/performance/development/home.htm">Learn more</a>.</p>
    </li>
    <!-- F10 DFV -->
    <!-- <li>
    <a href="/hr/staff-health-wellbeing/domestic-family-violence/supporting-someone.htm"><img src="/hr/images/home-slider/2017-08-28_DFV.jpg" alt="Domestic and family violence is a workplace issue. Help is available." /></a>
    <p class="title">Don't stay silent?</p>
    <p><a href="/hr/staff-health-wellbeing/domestic-family-violence/supporting-someone.htm">Support</a> is available to all affected.</p>
</li> -->
    <!-- F14 DFV We can make a difference
        <div>
            <a href="/hr/staff-health-wellbeing/domestic-family-violence/supporting-someone.htm"><img src="/hr/images/home-slider/2017-10-05_dfv.jpg" alt="Do you know how to help?" /></a>
            <p class="title">Do you know how to help?</p>
            <p>Check out the<a href="/hr/staff-health-wellbeing/domestic-family-violence/supporting-someone.htm"> resources, tools and policies</a> available to assist.</p>
        </div> -->
    <!-- C3 WRA Survey Open -->
    <!-- <li>
    <a href="/hr/staff-health-wellbeing/white-ribbon/survey.htm"><img src="/hr/images/home-slider/2017-08-29_WRAS.jpg" alt="White Ribbon survey now open. Complete today!" /></a>
    <p class="title">Domestic and family violence is a workplace issue.</p>
    <p><a href="/hr/staff-health-wellbeing/white-ribbon/survey.htm">Make a difference today!</a></p>
</li> -->
</ul>
