<div id="rightcolumn">
    <div class="hr-logo"><img src="/hr/images/Human-Resources-logo.png" alt="Human Resources Department of Health" /></div>
    <!-- #include virtual="/hr/include/master-search.inc" -->
    <!-- BEGIN Training calendar section -->
    <div class="sidebar_section">
        <h3 class="sidebar" style="background-color:#5eac61;">Training calendar</h3>
        <div class="quick_links">
            <ul class="fa-ul">
                <li>
                    <i class="fa-li fa fa-calendar-check-o fa-lg" aria-hidden="true"></i>25/10: <a href="https://ilearncatalogue.health.qld.gov.au/course/602/doh-corp-c-communicating-effectively-at-work-20102017">Communicating effectively at work </a></li>
                <li>
                    <i class="fa-li fa fa-calendar-check-o fa-lg" aria-hidden="true"></i>07/11: <a href="https://ilearncatalogue.health.qld.gov.au/course/586/doh-corp-c-coaching-for-performance-7112017">Coaching for performance</a></li>
                <li>
                    <i class="fa-li fa fa-calendar-check-o fa-lg" aria-hidden="true"></i>07/11: <a href="https://ilearncatalogue.health.qld.gov.au/course/639/doh-corp-c-real-conversations-managing-difficult-conversations">Real conversations</a></li>
            </ul>
            <p><a href="/hr/learning/training-calendar.htm">View full calendar >></a></p>
        </div>
    </div>
    <!-- END Training calendar section -->
    <!-- BEGIN CSP login section -->
    <div class="sidebar_section">
        <h3 class="sidebar" style="background-color:#4d98d1;">Career Success Plan (CSP)</h3>
        <div class="quick_links">
            <!--<p>Login to create or update your CSP.</p>-->
            <ul class="fa-ul">
                <li>
                    <i class="fa-li fa fa-wifi fa-lg" aria-hidden="true"></i><a href="http://qheps.health.qld.gov.au/hr/training-development/performance/development/home.htm"> Login</a> to create or update your CSP.</li>
                <!-- Customise with sub-site contact's direct email -->
                </li>
            </ul>
        </div>
    </div>
    <!-- END CSP login section -->
    <!-- BEGIN Contact section -->
    <div class="sidebar_section">
        <h3 class="sidebar">Contacts</h3>
        <div class="quick_links">
            <ul class="fa-ul">
                <li>
                    <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><strong><a href="mailto:HRConnect@health.qld.gov.au">Email HR Connect</a></strong>
                    <!-- Customise with sub-site contact's direct email -->
                </li>
                <li>
                    <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="/hr/contacts/local-hr-units.htm">Contact your local HR</a></strong>
                </li>
            </ul>
        </div>
    </div>
    <!-- END Contact section -->
    <div class="opm-logo"><img src="/hr/images/Our-People-Matter_logo.png" alt="Our people matter" width=170></div>
</div>