<div id="container">
  <ul id="nav">
    <li><a href="/hr/home.htm">HR home&nbsp;&nbsp;| </a>
      <ul>
        <li><a href="/hr/about_us/home.htm">About HR Branch</a></li>
      </ul>
    </li>
    <li><a href="#" class="not-active">Workplace culture&nbsp;&nbsp;|</a>
      <ul>
        <li><a href="/hr/culture/home.htm">Our culture</a></li>
        <li><a href="/hr/workplace-culture/code-of-conduct/home.htm">Code of conduct</a></li>
        <li><a href="/hr/diversity-inclusion/home.htm">Diversity inclusion and engagement</a></li>
        <li><a href="/hr/leadership/profiles.htm">Leader profiles</a></li>
        <li><a href="/hr/culture/sparks/home.htm">Spark network</a></li>
        <li><a href="/hr/employee-opinion-survey/home.htm">Working for Queensland Survey</a></li>
        <li><a href="/hr/employee-complaints/home.htm">Employee complaints</a></li>
      </ul>
    </li>
    <li><a href="#" class="not-active">Pay, leave &amp; benefits&nbsp;&nbsp;|</a>
      <ul>
        <li><a href="/paris/employees/leave.htm">Applying for leave</a></li>
        <li><a href="/hr/pay-leave-benefits/wage-rates/home.htm">Wage rates</a></li>
        <li><a href="/streamline/">Payroll self service (Streamline)</a></li>
        <li><a href="/paris/employees/home.htm">Payroll processes for employees</a></li>
        <li><a href="/paris/managers/home.htm">Payroll processes for managers</a></li>
        <li><a href="/paris/reporting/home.htm">Roster management (Workbrain)</a></li>
        <li><a href="/hr/pay-leave-benefits/salary-packaging/home.htm">Salary packaging</a></li>
        <li><a href="/hr/pay-leave-benefits/superannuation/home.htm">Superannuation</a></li>
        <li><a href="/hr/staff-wellness/corporate-discounts/home.htm">Corporate discounts</a></li>
      </ul>
    </li>
    <li><a href="#" class="not-active">Policies, agreements &amp; directives&nbsp;&nbsp;|</a>
      <ul>
        <li><a href="/hr/employment-conditions/policies-index.htm">HR policy index</a></li>
        <li><a href="/hr/circulars/home.htm">HR circulars (updates)</a></li>
        <li><a href="/hr/policies-agreements-directives/awards-agreements/home.htm">Awards &amp; agreements</a></li>
        <li><a href="/hr/policies-agreements-directives/enterprise-bargaining/home.htm">Enterprise bargaining and negotiations</a></li>
        <li><a href="/hr/policies-agreements-directives/health-employment-directives/home.htm">Health employment directives</a></li>
        <li><a href="/hr/policies-agreements-directives/psc-directives/home.htm">PSC & IR directives</a></li>
        <li><a href="/hr/policies-agreements-directives/delegations/home.htm">HR delegations manuals</a></li>
        <li><a href="/hr/pay-leave-benefits/smo-advancement/home.htm">Senior medical officer advancement</a></li>
        <li><a href="/hr/policies-agreements-directives/union-encouragement/home.htm">Union encouragement</a></li>
      </ul>
    </li>
    <li><a href="#" class="not-active">Workplace health &amp; safety&nbsp;&nbsp;|</a>
      <ul>
        <li><a href="/safety/sms/home.htm">Safety management system</a></li>
        <li><a href="/safety/employees/emergencies.htm">Emergency management</a></li>
        <li><a href="/safety/employees/incident_reporting.htm">Reporting incidents</a></li>
        <li><a href="/safety/employees/first-aid.htm">First aid in the workplace</a></li>
        <li><a href="/safety/ergo/resources_office.htm">Workstation ergonomics</a></li>
        <li><a href="/safety/occup_violence/home.htm">Occupational Violence Prevention</a></li>
        <li><a href="/hr/html/health-safety.htm">OHS practitioners tools</a></li>
      </ul>
    </li>
    <li><a href="#" class="not-active">Staff health &amp; wellbeing&nbsp;&nbsp;|</a>
      <ul>
        <li><a href="/hr/staff-wellness/healthy-workplace/home.htm">Healthy workplaces</a></li>
        <li><a href="/hr/staff-wellness/home.htm">Wellness index</a></li>
        <li><a href="/hr/staff-vaccinations/home.htm">Staff vaccinations</a></li>
        <li><a href="/hr/staff-wellness/mentally-healthy/home.htm">Mental wellness program</a></li>
        <li><a href="/hr/staff-health-wellbeing/domestic-family-violence/home.htm">Domestic and family violence</a></li>
        <li><a href="/hr/staff-health-wellbeing/white-ribbon/home.htm">White ribbon accreditation</a></li>
        <li><a href="/eap/html/MgrAssist.htm">Managers assist</a></li>
        <li><a href="/eap/">Employee assistance</a></li>
      </ul>
    </li>
    <li><a href="#" class="not-active">Ethics &amp; conduct&nbsp;&nbsp;|</a>
      <ul>
        <li><a href="/hr/performance/home.htm">Behaviour &amp; performance</a></li>
        <li><a href="/hr/workplace-culture/code-of-conduct/home.htm">Code of conduct</a></li>
        <li><a href="/hr/corrupt-conduct/home.htm">Corrupt conduct</a></li>
        <li><a href="/hr/corrupt-conduct/criminal-matters.htm">Criminal matters</a></li>
        <li><a href="/hr/pid/home.htm">Public interest disclosure</a></li>
      </ul>
    </li>
    <li><a href="#" class="not-active">Careers &amp; recruitment&nbsp;&nbsp;|</a>
      <ul>
        <li><a href="/hr/recruitment/home.htm">Processes</a></li>
        <li><a href="/hr/weg/">Job evaluation</a></li>
        <li><a href="/hr/weg/html/rdlibrary.htm">Role descriptions</a></li>
        <li><a href="/hr/visa-and-immigration/home.htm">Visa &amp; immigration</a></li>
        <li><a href="/hr/onboarding/home.htm">Onboarding</a></li>
        <li><a href="/hr/onboarding/orientation/home.htm">Orientation</a></li>
        <li><a href="/hr/erp/erp-home.htm">Employees requiring placement</a></li>
        <li><a href="https://www.health.qld.gov.au/employment">Work for us (internet)</a></li>
        <li><a href="https://www.health.qld.gov.au/employment/work-for-us/clinical/nursing-midwifery/graduate-campaigns">Graduate campaigns</a></li>
      </ul>
    </li>
    <li><a href="#" class="not-active">Learning &amp; leadership&nbsp;&nbsp;|</a>
      <ul>
        <li><a href="/hr/leadership/home.htm">Leadership development</a></li>
        <li><a href="/hr/mentoring/home.htm">Mentoring program</a></li>
        <li><a href="/hr/next-generation/home.htm">Future leaders (Next generation)</a></li>
        <li><a href="/ilearn/">Online learning</a></li>
        <li><a href="/hr/learning/training-calendar.htm">Training calendar</a></li>
        <li><a href="/hr/pdp/performance-dev-planning.htm">PDP</a></li>
        <li><a href="/hr/onboarding/mandatory.htm">Mandatory training</a></li>
        <li><a href="/hr/womens-network/home.htm">Womens Network</a></li>
      </ul>
    </li>
    <li><a href="#" class="not-active">Forms &amp; templates&nbsp;&nbsp;|</a>
      <ul>
        <li><a href="/hr/recruitment/employment-screening/home.htm">Employment screening</a></li>
        <li><a href="/hr/online/home.htm">Online publishing</a></li>
        <li><a href="/paris/forms/home.htm">Payroll &amp; rostering forms (PARIS)</a></li>
        <li><a href="/hr/pdp/performance-dev-planning.htm">PDP &ndash; Performance and development</a></li>
        <li><a href="/hr/recruitment/start-recruiting/filling-a-vacancy.htm#role">Role descriptions</a></li>
      </ul>
    </li>
    <li><a href="#" class="not-active">Contacts&nbsp;&nbsp;|</a>
      <ul>
        <li><a href="/hr/contacts/local-hr-units.htm">Local HR units</a></li>
        <li><a href="/hr/contacts/local-hr-units.htm#doh">Department of Health</a></li>
        <li><a href="/hr/contacts/eds-workforce.htm">Executive Directors Workforce</a></li>
        <li><a href="/hr/contacts/hrsbranch.htm">HR Branch</a></li>
        <li><a href="/safety/communications/contact_us2.htm">Workplace health &amp; safety </a></li>
      </ul>
    </li>
  </ul>
</div>
