<div id="nav2"><a name="sidenav"></a>
    <h3 class="sidebar">In this section</h3>
<!--beginnoindex-->
  <ul id="nav2xc">

        <li><a href="#">Online publishing</a>

	  </li>

<!--endnoindex-->

        <li><a href="/hr/online/html/approvals.htm">Publishing approval process</a>

	  </li>

<!--endnoindex-->

        <li><a href="/hr/online/docs/hrs_online_pub_form.pdf">Publishing Approval form</a>

	  </li>

<!--endnoindex-->

        <li><a href="/oim/governance/home.htm">Policy and Standards</a>

	  </li>

<!--endnoindex-->

        <li><a href="/oim/help/statistics/home.htm">Website statistics</a>

	  </li>

<!--endnoindex-->

        <li><a href="#">Tips and resources</a>

				<ul id="Tips and resources">

				<li><a href="/oim/help/home.htm">Publisher help and advice</a></li>

			  </ul></li>

<!--endnoindex-->

        <li><a href="mailto:johanna_brands@health.qld.gov.au">Contacts and feedback</a>

	  </li>

<!--endnoindex-->

  </ul>
</div>
