<div id="nav2">
    <a name="sidenav"></a>
    <h3 class="sidebar">Pay, leave &amp; benefits</h3>
    <!--beginnoindex-->
    <ul id="nav2xc">
      <li><a href="/paris/employees/leave.htm">Applying for leave</a></li>

      <!--endnoindex-->

      <li><a href="/hr/pay-leave-benefits/wage-rates/home.htm">Wage rates</a></li>

      <!--endnoindex-->

      <li><a href="/streamline/">Payroll self service (Streamline)</a></li>

      <!--endnoindex-->

      <li><a href="/paris/employees/home.htm">Payroll processes for employees</a></li>

      <!--endnoindex-->

      <li><a href="/paris/managers/home.htm">Payroll processes for managers</a></li>

      <!--endnoindex-->

      <li><a href="/paris/reporting/home.htm">Roster management (Workbrain)</a></li>

      <!--endnoindex-->

      <li><a href="/hr/pay-leave-benefits/salary-packaging/home.htm">Salary packaging</a></li>

      <!--endnoindex-->

      <li><a href="/hr/pay-leave-benefits/superannuation/home.htm">Superannuation</a></li>

      <!--endnoindex-->

      <li><a href="/hr/staff-wellness/corporate-discounts/home.htm">Corporate discounts</a></li>

        <!--endnoindex-->

      <li></li> <!--blank spacer. needed as QHEPS shell table styles conflict with custom styles here -->

    </ul>
</div>