<div id="nav2">
	<a name="sidenav"></a>
	<h3 class="sidebar">Policies, agreements &amp; directives</h3>
	<!--beginnoindex-->
	<ul id="nav2xc">
		<li><a href="/hr/policies-agreements-directives/policy-index/home.htm">Policy index</a>
			<ul id="Policy-index">
				<li><a href="/hr/policies-agreements-directives/policy-index/home.htm#a">A. Employment framework</a></li>
				<li><a href="/hr/policies-agreements-directives/policy-index/home.htm#b">B. Resourcing</a></li>
				<li><a href="/hr/policies-agreements-directives/policy-index/home.htm#c">C. Remuneration, leave and benefits</a></li>
				<li><a href="/hr/policies-agreements-directives/policy-index/home.htm#d">D. Relocation, accomodation and travel</a></li>
				<li><a href="/hr/policies-agreements-directives/policy-index/home.htm#e">E. Ethics and conduct</a></li>
				<li><a href="/hr/policies-agreements-directives/policy-index/home.htm#f">F. Consultation</a></li>
				<li><a href="/hr/policies-agreements-directives/policy-index/home.htm#g">G. Learning, development and performance</a></li>
				<li><a href="/hr/policies-agreements-directives/policy-index/home.htm#h">H. Separation of employment</a></li>
				<li><a href="/hr/policies-agreements-directives/policy-index/home.htm#i">I. Other</a></li>
			</ul>
		</li>
		<!--endnoindex-->
		<li><a href="/hr/circulars/home.htm">HR circulars (updates)</a></li>
		<!--endnoindex-->
		<li><a href="/hr/policies-agreements-directives/awards-agreements/home.htm">Awards &amp; agreements</a></li>
		<!--endnoindex-->
		<li><a href="/hr/employment-conditions/home.htm">Employment conditions</a>
			<ul id="Employment conditions">
				<li><a href="/hr/employment-conditions/streams/administrative.htm">Administrative officers</a></li>
				<li><a href="/hr/employment-conditions/streams/bems.htm">Building, engineering and maintenance</a></li>
				<li><a href="/hr/employment-conditions/streams/operational.htm">Operational officers</a></li>
				<li><a href="/hr/employment-conditions/streams/professional.htm">Professional officers</a></li>
				<li><a href="/hr/employment-conditions/streams/technical.htm">Technical officers</a></li>
			</ul>
		</li>
		<!--endnoindex-->
		<li><a href="/hr/policies-agreements-directives/enterprise-bargaining/home.htm">Enterprise bargaining and negotiations</a>
			<ul id="enterprise bargaining">
				<li><a href="/hr/policies-agreements-directives/enterprise-bargaining/nurses-midwives/home.htm">Nurses &amp; midwives</a>
					<br>
					<div>
<a href="/hr/policies-agreements-directives/enterprise-bargaining/nurses-midwives/num-mum-eb9-implementation.htm">NUM &amp; MUM</a>
<br>
<a href="/hr/policies-agreements-directives/enterprise-bargaining/nurses-midwives/career-classification.htm">Career &amp; Classification</a>
<br>
<a href="/hr/policies-agreements-directives/enterprise-bargaining/nurses-midwives/rural-remote-dons.htm">Rural and remote directors of nursing</a>
<br>
<a href="/hr/policies-agreements-directives/enterprise-bargaining/nurses-midwives/retention-initiatives.htm">Retention initiatives project</a>
<br>
<a href="/hr/policies-agreements-directives/enterprise-bargaining/nurses-midwives/summit.htm">NUM/MUMs summit</a>

					</div>
				</li>
			</ul>
		</li>
		<!--endnoindex-->
		<li><a href="/hr/policies-agreements-directives/health-employment-directives/home.htm">Health employment directives</a></li>
		<!--endnoindex-->
		<li><a href="/hr/policies-agreements-directives/psc-directives/home.htm">PSC and IR directives</a></li>
		<!--endnoindex-->
		<li><a href="/hr/policies-agreements-directives/delegations/home.htm">HR delegations</a></li>
		<!--endnoindex-->
		<li><a href="/hr/policies-agreements-directives/industrial-relations/home.htm">Industrial relations</a></li>
		<!--endnoindex-->
		<li><a href="/hr/pay-leave-benefits/smo-advancement/home.htm">Senior medical officer advancement</a></li>
		<!--endnoindex-->
		<li><a href="/hr/policies-agreements-directives/union-encouragement/home.htm">Union encouragement</a></li>
		<!--endnoindex-->
		<li></li>
		<!--blank spacer. needed as QHEPS shell table styles conflict with custom styles here -->
	</ul>
</div>
