<div id="nav2"><a name="sidenav"></a>
    <h3 class="sidebar">Recruitment</h3>
    <!--beginnoindex-->
    <ul id="nav2xc">
        <li><a href="/hr/recruitment/home2.htm">Recruitment home</a></li>
        <!--endnoindex-->
        <li><a href="/hr/recruitment/getting-started/home.htm">Getting started</a>
            <ul id="Getting started">
                <li><a href="/hr/recruitment/getting-started/verbal-approval.htm">Verbal approval</a></li>
                <li><a href="/hr/recruitment/getting-started/establishment-review.htm">Establishment review</a></li>
                <li><a href="/hr/recruitment/getting-started/review-role.htm">Review the role</a></li>
                <li><a href="/hr/recruitment/getting-started/prepare-description.htm">Prepare a new role description</a></li>
                <li><a href="/hr/recruitment/getting-started/role-evaluation.htm">Role evaluation</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li><a href="/hr/recruitment/options-to-fill/home.htm">Options to fill</a>
            <ul id="Options to fill">
                <li><a href="/hr/recruitment/options-to-fill/temporary.htm">Temporary</a></li>
                <li><a href="/hr/recruitment/options-to-fill/temporary.htm">Permanent</a></li>
                <li><a href="/hr/recruitment/options-to-fill/temporary.htm">Direct appointment</a></li>
                <li><a href="/hr/recruitment/options-to-fill/temporary.htm">Merit</a></li>
                <li><a href="/hr/recruitment/options-to-fill/temporary.htm">EOIs</a></li>
                <li><a href="/hr/recruitment/options-to-fill/temporary.htm">Using an agency</a></li>
                <li><a href="/hr/recruitment/options-to-fill/temporary.htm">Workforce succession options</a></li>
                <li><a href="/hr/recruitment/options-to-fill/temporary.htm">Employees requiring placement</a></li>
                <li><a href="/hr/recruitment/options-to-fill/temporary.htm">Referrals</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li><a href="/hr/recruitment/advertising/home.htm">Advertising</a>
            <ul id="Advertising">
                <li><a href="/hr/recruitment/advertising/request-to-hire.htm">Request to hire</a></li>
                <li><a href="/hr/recruitment/advertising/internal-advertising.htm">Internal advertising</a></li>
                <li><a href="/hr/recruitment/advertising/external-advertising.htm">External advertising</a>
                    <div>
                        <a href="/hr/recruitment/advertising/role-brief.htm">Role brief</a>
                        <br>
                        <a href="/hr/recruitment/advertising/planning.htm">Planning (timeframes)</a>
                    </div>
                </li>
            </ul>
        </li>
        <!--endnoindex-->
        <li><a href="/hr/recruitment/selection-and-assessment/home.htm">Selection and assessment</a>
            <ul id="Selection and assessment">
                <li><a href="/hr/recruitment/selection-and-assessment/arrange-your-ppanel.htm">Arrange your panel</a></li>
                <li><a href="/hr/recruitment/selection-and-assessment/longlisting.htm">Longlisting</a></li>
                <li><a href="/hr/recruitment/selection-and-assessment/shortlisting.htm">Shortlisting</a></li>
                <li><a href="/hr/recruitment/selection-and-assessment/phone-screening.htm">Phone screening</a></li>
                <li><a href="/hr/recruitment/selection-and-assessment/interview-strategies.htm">Interview strategies</a></li>
                <li><a href="/hr/recruitment/selection-and-assessment/behavioural-interviews.htm">Behavioural interviews</a></li>
                <li><a href="/hr/recruitment/selection-and-assessment/skills-assessment.htm">Skills assessment</a></li>
                <li><a href="/hr/recruitment/selection-and-assessment/selection-techniques.htm">Selection techniques</a></li>
                <li><a href="/hr/recruitment/selection-and-assessment/work-samples.htm">Work Samples</a></li>
                <li><a href="/hr/recruitment/selection-and-assessment/psychometrics.htm">Psychometrics</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li><a href="/hr/recruitment/pre-employment-checks/home.htm">Pre-employment Checks</a>
            <ul id="Pre-employment Checks">
                <li><a href="/hr/recruitment/pre-employment-checks/referees-checks.htm">Referees checks</a></li>
                <li><a href="/hr/recruitment/pre-employment-checks/criminal-history.htm">Criminal history</a></li>
                <li><a href="/hr/recruitment/pre-employment-checks/vaccinations.htm">Vaccinations</a></li>
                <li><a href="/hr/recruitment/pre-employment-checks/etc.htm">etc.?</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li><a href="/hr/recruitment/selection-and-offer/home.htm">Selection and offer</a>
            <ul id="Selection and offer">
                <li><a href="/hr/recruitment/selection-and-offer/verbal-offer.htm">Verbal offer</a></li>
                <li><a href="/hr/recruitment/selection-and-offer/written-offer.htm">Written offer</a></li>
                <li><a href="/hr/recruitment/selection-and-offer/selection-reports.htm">Selection reports</a></li>
                <li><a href="/hr/recruitment/selection-and-offer/appointment-documents.htm">Appointment documents</a></li>
                <li><a href="/hr/recruitment/selection-and-offer/no-success-letter.htm">No success letter</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li><a href="/hr/recruitment/prepare-for-a-new-starter/home.htm">Prepare for a new starter</a>
            <ul id="Prepare for a new starter">
                <li><a href="/hr/recruitment/prepare-for-a-new-starter/probation.htm">Probation</a></li>
                <li><a href="/hr/recruitment/prepare-for-a-new-starter/mandatory-training.htm">Mandatory training</a></li>
                <li><a href="/hr/recruitment/prepare-for-a-new-starter/csp.htm">CSP</a></li>
                <li><a href="/hr/recruitment/prepare-for-a-new-starter/orientation.htm">Orientation</a></li>
                <li><a href="/hr/recruitment/prepare-for-a-new-starter/local-induction.htm">Local induction</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li></li>
        <!--blank spacer. needed as QHEPS shell table styles conflict with custom styles here -->
    </ul>
</div>