<div class="sidebar_section">
  <h3 class="sidebar">Search HR Branch</h3>
  <div id="sidebar_search">
    <script type="text/javascript" src="http://qheps.health.qld.gov.au/_includes/scripts/funnelback.js"></script>
    <form action="javascript: fbsearch('s-search','qheps.health.qld.gov.au/hr');" name="s-search"><input name="query" size="25" type="text" /> <input id="submitbut" type="submit" value="" /><!--<i class="fa fa-search fa-lg" aria-hidden="true"></i>--></form>
  </div>
</div>
