<div id="nav2">
    <a name="sidenav"></a>
    <h3 class="sidebar">Staff health &amp; wellbeing</h3>
    <!--beginnoindex-->
    <ul id="nav2xc">
        <li><a href="/hr/staff-health-wellbeing/staff-wellbeing/home.htm">Staff wellbeing</a>
            <ul id="Staff wellbeing">
                <li><a href="/hr/staff-health-wellbeing/staff-wellbeing/mental-wellbeing/home.htm">Mental wellbeing employee resources</a>
                    <br>
                    <div>
                        <a href="/hr/staff-health-wellbeing/staff-wellbeing/mental-wellbeing/workplace-mental-health.htm">Mentally healthy workplaces</a>
                        <br>
                        <a href="/hr/staff-health-wellbeing/staff-wellbeing/mental-wellbeing/mental-health-wellbeing-framework.htm">Workplace mental health &amp; wellbeing framework</a>
                        <br>
                    </div>
                </li>
                <li><a href="/hr/staff-health-wellbeing/staff-wellbeing/social-wellbeing/home.htm">Social wellbeing</a></li>
                <li><a href="/hr/staff-health-wellbeing/staff-wellbeing/financial-wellbeing/home.htm">Financial wellbeing</a>
                    <br>
                    <div>
                        <a href="/hr/staff-health-wellbeing/staff-wellbeing/financial-wellbeing/corporate-discounts.htm">Corporate discounts</a>
                        <br>
                    </div>
                </li>
                <li><a href="/hr/staff-health-wellbeing/staff-wellbeing/physical-wellbeing/home.htm">Physical wellbeing</a></li>
                <li><a href="/hr/staff-health-wellbeing/staff-wellbeing/event-calendar.htm">Events calendar</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li class="xc"><a href="/hr/staff-vaccinations/home.htm">Staff vaccinations</a>
            <ul id="Staff vaccinations">
                <li><a href="/hr/staff-vaccinations/mandatory/home.htm">Mandatory vaccinations</a></li>
                <li><a href="/hr/staff-vaccinations/flu/home.htm">Staff influenza vaccinations</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li class="xc"><a href="/hr/staff-health-wellbeing/domestic-family-violence/home.htm">Domestic and family violence</a>
            <ul id="Domestic and family violence">
                <li><a href="/hr/staff-health-wellbeing/domestic-family-violence/what-is.htm">What is domestic and family violence?</a></li>
                <li><a href="/hr/staff-health-wellbeing/domestic-family-violence/supporting-someone.htm">Supporting someone</a></li>
                <li><a href="/hr/staff-health-wellbeing/domestic-family-violence/help-lines.htm">Helplines and referrals</a></li>
                <li><a href="/hr/staff-health-wellbeing/domestic-family-violence/policy-pledge-directive.htm">Policy and guideline</a></li>
                <li><a href="/hr/staff-health-wellbeing/domestic-family-violence/champions-network.htm">Champions network</a></li>
                <li><a href="/hr/staff-health-wellbeing/domestic-family-violence/activities.htm">Activities</a></li>
                <li><a href="/hr/staff-health-wellbeing/domestic-family-violence/resources.htm">Resources</a></li>
                <li><a href="/hr/staff-health-wellbeing/domestic-family-violence/training.htm">Online training</a></li>
                <li><a href="/hr/staff-health-wellbeing/white-ribbon/accreditation.htm">White Ribbon accreditation</a></li>
                <li><a href="/hr/staff-health-wellbeing/white-ribbon/what-is.htm">White Ribbon Australia</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li class="xc"><a href="/hr/staff-health-wellbeing/white-ribbon/home.htm">White Ribbon workplace accreditation</a>
            <ul id="White ribbon accreditation">
                <li><a href="/hr/staff-health-wellbeing/white-ribbon/accreditation.htm">Program</a></li>
                <li><a href="/hr/staff-health-wellbeing/white-ribbon/statistics.htm">Statistics</a></li>
                <li><a href="/hr/staff-health-wellbeing/white-ribbon/committee.htm">Committee</a></li>
                <li><a href="/hr/staff-health-wellbeing/white-ribbon/survey.htm">Survey</a></li>
                <li><a href="/hr/staff-health-wellbeing/white-ribbon/activities.htm">Activities</a></li>
                <li><a href="/hr/staff-health-wellbeing/white-ribbon/what-is.htm">What is White Ribbon Australia?</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li class="xc"><a href="/hr/staff-health-wellbeing/counselling-support/home.htm">Counselling and support</a>
            <ul id="Counselling & support">
                <li><a href="/hr/staff-health-wellbeing/counselling-support/employee-counselling.htm">Employee counselling</a></li>
                <li><a href="/hr/staff-health-wellbeing/counselling-support/manager-support.htm">Manager support</a></li>
                <li><a href="/hr/staff-health-wellbeing/counselling-support/crisis-support.htm">Crisis support</a></li>
                <li><a href="/hr/staff-health-wellbeing/counselling-support/faqs-eap.htm">FAQs</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li></li>
        <!--blank spacer. needed as QHEPS shell table styles conflict with custom styles here -->
    </ul>
</div>