<div id="nav2">
    <a name="sidenav"></a>
    <h3 class="sidebar">Training and development</h3>
    <!--beginnoindex-->
    <ul id="nav2xc">
        <li><a href="https://ilearncatalogue.health.qld.gov.au/">Online course catalogue</a></li>
        <!--endnoindex-->
        <li><a href="/hr/learning/training-calendar.htm">Training calendar</a></li>
        <!--endnoindex-->
        <li><a href="/hr/onboarding/mandatory.htm">Mandatory training</a></li>
        <!--endnoindex-->
        <li><a href="/ilearn">Online training (iLearn)</a></li>
        <!--endnoindex-->
        <li><a href="/hr/training-development/strategy/performance-capability-recognition/home.htm">Performance, Capability &amp; Recognition</a>
            <ul id="Performance, Capability &amp; Recognition">
                <li><a href="/hr/training-development/performance/development/home.htm">Performance development</a>
                    <br>
                    <div>
                        <a href="/hr/pdp/performance-dev-planning.htm">Paper-based PDP</a>
                    </div>
                </li>
                <li><a href="/hr/training-development/learning/home.htm">Capability development</a></li>
                <li><a href="/hr/training-development/recognition/home.htm">Recognition</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li><a href="/hr/training-development/performance/management/home.htm">Performance reviews and discipline</a></li>
        <!--endnoindex-->
        <li><a href="/hr/mentoring/home.htm">Mentoring</a>
            <ul id="Mentoring">
                <li><a href="/hr/mentoring/videos.htm">Mentoring videos</a></li>
                <li><a href="/hr/mentoring/vision.htm">Vision and objectives</a></li>
                <li><a href="/hr/mentoring/mentor-me/home.htm">MentorMe</a>
                    <br>
                    <div>
                        <a href="/hr/mentoring/be-a-mentor/about.htm">Be a mentor</a>
                        <br>
                        <div>
                            <a href="/hr/mentoring/be-a-mentor/support-resources.htm">Support &amp; resources</a>
                            <br>
                            <a href="/hr/mentoring/be-a-mentor/FAQs.htm">FAQs</a>
                            <br>
                        </div>
                        <a href="/hr/mentoring/get-a-mentor/about.htm">Get a mentor</a>
                        <br>
                        <div><a href="/hr/mentoring/get-a-mentor/support-resources.htm">Support &amp; resources</a>
                            <br>
                            <a href="/hr/mentoring/get-a-mentor/FAQs.htm">FAQs</a></div>
                    </div>
                </li>
                <li><a href="/hr/mentoring/mentor-match/home.htm">MentorMatch</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li><a href="/hr/next-generation/home.htm">Future leaders (Next generation)</a></li>
        <!--endnoindex-->
        <!-- <li><a href="#">Executive development</a></li> -->
        <!--endnoindex-->
        <li><a href="/hr/leadership/home.htm">Leadership development</a>
            <ul id="Leadership development">
                <li><a href="/hr/leadership/strategy.htm">Leadership Development Strategy</a>
                    <div>
                        <a href="/hr/leadership/about.htm">About the Leadership Development Strategy</a>
                    </div>
                </li>
                <li><a href="/hr/leadership/profiles.htm">Leader profiles</a>
                    <div>
                        <a href="/hr/leadership/action-plans.htm">Action plans</a>
                        <br>
                        <a href="/hr/leadership/success-stories.htm">Success stories</a>
                        <br>
                        <a href="/hr/leadership/profile-resources.htm">Resources</a>
                    </div>
                </li>
                <li><a href="/hr/leadership/executives.htm">Executive program</a></li>
                <li><a href="/hr/leadership/leaders.htm">Leaders program</a></li>
                <li><a href="/hr/leadership/supervisors.htm">Supervisors program</a></li>
                <li><a href="/hr/learning/influencing-behaviours-for-success.htm">Influencing behaviours for success</a>
                    <br>
                    <div>
                        <a href="/hr/learning/influencing-behaviours-keynote.htm">Keynote</a>
                        <br>
                        <a href="/hr/learning/influencing-behaviours-workshop-a.htm">Workshop A</a>
                        <br>
                        <a href="/hr/learning/influencing-behaviours-workshop-b.htm">Workshop B</a>
                        <br>
                        <a href="/hr/learning/influencing-behaviours-resources.htm">Resources</a>
                    </div>
                </li>
                <li><a href="/hr/leadership/resources.htm">Resources</a></li>
                <li><a href="/hr/leadership/reports.htm">Reports</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li><a href="/hr/womens-network/home.htm">Women's network</a>
            <ul id="Womens network">
                <li><a href="/hr/womens-network/steering-committee.htm">Women's Network Steering Committee</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li></li>
        <!--blank spacer. needed as QHEPS shell table styles conflict with custom styles here -->
    </ul>
</div>