<div id="nav2">
    <a name="sidenav"></a>
    <h3 class="sidebar">Workplace health &amp; safety</h3>
    <!--beginnoindex-->
    <ul id="nav2xc">
        <!--endnoindex-->
        <li><a href="/safety/sms/home.htm">Safety management system</a>
        </li>
        <!--endnoindex-->
        <li><a href="/safety/employees/emergencies.htm">Emergency management</a>
        </li>
        <!--endnoindex-->
        <li><a href="/safety/employees/incident_reporting.htm">Reporting incidents</a>
        </li>
        <!--endnoindex-->
        <li><a href="/safety/employees/first-aid.htm">First aid in the workplace</a>
        </li>
        <!--endnoindex-->
        <li><a href="/safety/ergo/resources_office.htm">Workstation ergonomics</a>
        </li>
        <!--endnoindex-->
        <li><a href="/safety/occup_violence/home.htm">Occupational Violence Prevention</a>
        </li>
        <!--endnoindex-->
        <li><a href="/safety/ohs_tools.htm">OHS practitioners tools</a>
        </li>
        <!--endnoindex-->
        <li><a href="/hr/crrr/home.htm">Community Recovery Ready Reserve</a>
            <ul id="Community Recovery Ready Reserve">
                <li><a href="/hr/crrr/reservist-role.htm">Role of a reservist</a></li>
                <li><a href="/hr/crrr/become-a-reservist.htm">Become a reservist</a></li>
                <li><a href="/hr/crrr/reservist-support.htm">Supporting resources for reservists</a></li>
                <li><a href="/hr/crrr/enquiries.htm">Feedback and enquiries</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li></li>
        <!--blank spacer. needed as QHEPS shell table styles conflict with custom styles here -->
    </ul>
</div>