<!--START CUSTOM FOOTER-->
<!--#include virtual="/hr/include/main_footer-custom.inc" -->
<!--END CUSTOM FOOTER-->
<div id="footer_wrap">
    <div id="footer_top"></div>
</div>
<table width="100%" border="0" cellpadding="0" cellspacing="0" id="footer">
    <tr>
        <td><img src="/masters/menu/library/images/footer_qld_logo.gif" alt="Queensland Government | Queensland Health"></td>
        <td align="right"><strong><A href="http://qheps.health.qld.gov.au/masters/disclaimer.htm">Disclaimer</A> | <A href="http://qheps.health.qld.gov.au/masters/feedback.htm">Comments</A> | <A href="http://qheps.health.qld.gov.au/eps/pub_info.htm">Publishing</A> | <A href="http://qheps.health.qld.gov.au/masters/training.htm">Training<br><br></A>Copyright &copy; Queensland Government</strong></td>
    </tr>
    <tr>
        <td height="5"></td>
        <td height="5"></td>
    </tr>
    <tr>
        <td>Please note that any material printed is regarded as an uncontrolled copy. It is the responsibility of the person printing the document to refer frequently to QHEPS for updates.</td>
        <td align="right">For General HR enquiries and feedback contact
            <BR>
            <A href="mailto:HRConnect@health.qld.gov.au">HR Connect</A>
            <BR>
        </td>
    </tr>
</table>