<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Popular pages section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fas fa-link fa-lg" aria-hidden="true"></i><a href="/safety/sms/home.htm">Safety Management System</a></li>
            <li><i class="fa-li fas fa-link fa-lg" aria-hidden="true"></i><a href="/safety/employees/incident_reporting.htm">Reporting an Incident</a></li>
            <li><i class="fa-li fas fa-link fa-lg" aria-hidden="true"></i><a href="/safety/communications/alerts_notices.htm">Safety Alerts, Notices and Information</a></li>
            <li><i class="fa-li fas fa-link fa-lg" aria-hidden="true"></i><a href="/safety/elearning.htm">Online learning environment</a></li>
            <li><i class="fa-li fas fa-link fa-lg" aria-hidden="true"></i><a href="/safety/communications/circulars.htm">Safety Circulars</a></li>
            <li><i class="fa-li fas fa-link fa-lg" aria-hidden="true"></i><a href="/safety/communications/newsletters.htm">Publications</a></li>
        </ul>
    </div>
</div>
<!-- END Supporting resources section -->
<!-- BEGIN Related links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Supporting resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fas fa-file-pdf fa-lg" aria-hidden="true"></i><a href="/safety/safety_topics/strategic_plan/OrgHeathStratPlan.pdf">Organisational Health Strategic Plan 2012&ndash;2016</a> (PDF, 518kB)</li>
        </ul>
    </div>
</div>
<!-- END Related links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fas fa-phone fa-lg" aria-hidden="true"></i><a href="/hr/contacts/whs.htm">Contact Work, Health & Safety</a>
                <!-- Customise with sub-site contact's direct email -->
            </li>
            <li><i class="fa-li fas fa-envelope fa-lg" aria-hidden="true "></i><a href="mailto:HRConnect@health.qld.gov.au">Email HR Connect</a></li>
        </ul>
    </div>
</div>
<!-- END Contact section -->