<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->

<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
  <h3 class="sidebar">Shortcuts</h3>
  <div class="quick_links">
    <ul class="fa-ul">
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://qheps.health.qld.gov.au/governance/fraud/training.htm">Ethics awareness and fraud control training</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://qheps.health.qld.gov.au/governance/risk/framework.htm">Updated Risk Management Framework</a></li>
    </ul>
  </div>
</div>
<!-- END Quick Links section -->

<!-- BEGIN Contact section -->
<div class="sidebar_section">
  <h3 class="sidebar">Contact us</h3>
  <div class="quick_links">
    <p><strong>Ethical Standards Unit</strong></p>
    <ul class="fa-ul">
      <li>
        <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><strong><a href="mailto:co_complaints@health.qld.gov.au">email us</a></strong>
        <!-- Customise with sub-site contact's direct email -->
      </li>
      <li>
        <!-- Customise with the sub-site's direct email contact -->
        <i class="fa-li fa fa-phone fa-lg" aria-hidden="true"></i>Phone: (07) 3708 5414</a>
      </li>
    </ul>
  </div>
</div>
<!-- END Contact section -->
