
<style type="text/css"> <!--

.r4f_forms input	{
	width: 100%; 
	background: #fafafa; 
	border: 1px solid #ccc; 
	height: 30px; 
}

.r4f_forms .r4f_textarea input, .r4f_forms select	{
	width: 100%; 
	background: #fafafa; 
	border: 1px solid #ccc; 
	height: 30px;
}

.r4f_forms .r4f_textarea input	{
	height: 150px;
	width: 100%; 
	border-radius: 12px; 
	vertical-align: top;
}

#r4f_form_wrapper	{ 
	border-radius: 10px; 
	color: #fff; 
	padding: 20px; 
	background: #eee9e9; 
	margin: 0 0 10px 0;
}

.r4f_table	{
	width: 100%;
}

.r4f_table td	{
	border: 1px solid #ddd; 
	padding: 20px; 
	background: #ededed; 
	border-radius: 8px;
}

.r4f_table td.down_arrow	{
	border: 0px solid #fff; 
	padding: 0px; 
	background: #fff;
}

.r4f_table .green	{
	background: #9BBB59;
}

.r4f_table .green a	{
	color: #fff;
}

.r4f_table .darkgreen	{
	background: #5cb37c;
}

.r4f_table .darkgreen a	{
	color: #fff;
}

.r4f_table .blue	{
	background: #608cab;
}

.r4f_table .blue a	{
	color: #fff;
}

.r4f_table .darkblue	{
	background: #376092;
}

.r4f_table .darkpurple	{
	background: #8064A2;
}

.r4f_table .darkblue a	{
	color: #fff;
}
--></style>