<!-- Customise the sidebar links below as appropriate -->
<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Current activities</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="/hr/culture/connectedness/home.htm#current" title="Connectedness current activities">Connectedness</a></li>
            <li>
                <i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="/hr/culture/performance/home.htm#performance" title="Performance current activities">Performance</a></li>
            <li>
                <i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="/hr/culture/clarity/home.htm#clarity" title="Clarity current activities">Clarity</a></li>
            <li>
                <i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="/hr/culture/respect/home.htm#respect" title="Respect current activities">Respect</a></li>
            <li>
                <i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="/hr/culture/capability/home.htm#capability" title="Capability current activities">Capability</a></li>
        </ul>
    </div>
</div>
<!-- END Quick Links section -->
<!-- BEGIN Related links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hunterreview/home.htm" title="Hunter Review">Hunter review</a></li>
            <li>
                <i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/learning/training-calendar.htm">Training calendar</a></li>
            <li>
                <i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/leadership/profiles.htm">Leader profiles</a></li>
            <li>
                <i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/learning/influencing-behaviours-for-success.htm">Influencing behaviours for success</a></li>
            <li>
                <i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/training-development/strategy/performance-capability-recognition/home.htm">Performance, Capability & Recognition strategy</a></li>
        </ul>
    </div>
</div>
<!-- END Related links section -->
<!-- BEGIN Supporting resources section -->
<div class="sidebar_section">
    <h3 class="sidebar">Supporting resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/culture/docs/cultural-success-factors.pdf">Cultural success factors</a> (PDF, 436KB)</li>
            <li>
                <i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/dgdivision/docs/charter.pdf">Charter of responsibility</a> (PDF, 435KB)</li>
            <li>
                <i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/dgdivision/docs/model-statements.pdf">Functional model statements</a> (PDF, 886KB)</li>
        </ul>
    </div>
</div>
<!-- END Supporting resources section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <!-- Customise with sub-site contact's direct email -->
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><strong><a href="/hr/culture/sparks/contact-us.htm" title="Contact SPARKS">email us</a></strong>
            </li>
            <li>
                <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="/hr/contact/local-hr-contacts.htm">Contact your local HR</a></strong>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->