<div id="rightcolumn">
    <div class="hr-logo"><img src="/hr/images/Human-Resources-logo.png" alt="Human Resources Department of Health" /></div>
    <!--#include virtual="/hr/include/master-search.inc" -->
    <!-- Global search include -->
    <!-- Custom includes:
          * create an includes folder at the top-level of your sub-site folder
          * upload below file, replace 'sub-site' with the actual sub-site folder name: i.e. 'diversity-inclusion' -->
    <!--#include virtual="/hr/culture/include/quick_links-conduct.inc" -->
    <!-- #include virtual="/hr/include/aside-feedback.inc" -->
    <div class="opm-logo"><img src="/hr/images/Our-People-Matter_logo.png" alt="Our people matter" width=170></div>
</div>
<!-- Final step:
      To include this file, add or replace the HTML content of your RHS column section in the TeamSite editor with the following (including comment brackets). Again, replace 'sub-site' with the name of your enclosing folder and remove the square brackets around the #):
-->
<!-- [#]include virtual="/hr/sub-site/includes/right_column.inc" -->