Customise the sidebar links below as appropriate -->
<!-- BEGIN Related Links section -->
<!-- <div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="">Resources??</a></li>
        </ul>
    </div>
</div> -->
<!-- END Related Links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <!-- Customise with sub-site contact's direct email -->
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><a href="mailto:recruitforfit@health.qld.gov.au">Email recruitment</a>
            </li>
            <li>
                <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="/hr/contacts/local-hr-units.htm">Contact your local HR</a></strong>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section