<!-- Customise the sidebar links below as appropriate -->
<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Supporting resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="http://www.health.qld.gov.au/nonconsumer_complaint/docs/res_complaints.pdf">Guide for the resolution of informal complaints</a> (PDF, 530kb)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="http://qheps.health.qld.gov.au/safety/sms/docs/doh-tr-2014-mental-health.pdf">Supporting employees with mental illness</a> (PDF, 130kb)</li>
        </ul>
    </div>
</div>
<!-- END Quick Links section -->
<!-- BEGIN Related links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/safety/employees/incident_reporting.htm">Report a workplace incident</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/psu/prime/default.htm">PRIME</a> &ndash; clinical incidents and consumer feedback</li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.ombudsman.qld.gov.au/">Queensland Ombudsman</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.cmc.qld.gov.au/">Crime and&nbsp;Corruption Commission</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.qirc.qld.gov.au/">Queensland Industrial Relations Commission</a></li>
        </ul>
    </div>
</div>
<!-- END Related links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <!-- Customise with sub-site contact's direct email -->
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><a href="mailto:StaffCompliants@health.qld.gov.au">Email&nbsp;Employee complaints</a>
            </li>
            <li>
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><a href="mailto:co_complaints@health.qld.gov.au">Email Conduct Advisory Service</a>
            </li>
            <li>
                <i class="fa-li fa fa-phone fa-lg" aria-hidden="true"></i>Call 1800 195 240
            </li>
            <li>
                <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="/hr/contact/local-hr-contacts.htm">Contact your local HR</a></strong>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->