<div id="nav2">
    <a name="sidenav"></a>
    <h3 class="sidebar">Managers toolbox</h3>
    <!--beginnoindex-->
    <ul id="nav2xc">
        <li><a href="/hr/managers/home.htm">Home page</a></li>
        <li><a href="/hr/managers/performance-management.htm">Performance management</a>
            <ul id="Performance management">

                <li><a href="#">title</a></li>
                <li><a href="#">title</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li class="xc"><a href="/hr/managers/probation.htm">Probation</a>
            <ul id="Probation">
                <li><a href="#">title</a></li>
                <li><a href="#">title</a></li>
            </ul>
        </li>
        <!--endnoindex-->

        <li class="xc"><a href="/hr/managers/delegations-decision-making.htm">Delegations and decision making</a>
            <ul id="Decision making">
                <li><a href="#">title</a></li>
                <li><a href="#">title</a></li>
            </ul>
        </li>
        <!--endnoindex-->

        <li class="xc"><a href="/hr/managers/conflicts-of-interest.htm">Conflicts of interest</a>
            <ul id="Conflicts of interest">
                <li><a href="#">title</a></li>
                <li><a href="#">title</a></li>
            </ul>
        </li>
        <!--endnoindex-->

        <li class="xc"><a href="#">Workplace harassment</a>
            <ul id="Workplace harassment">
                <li><a href="#">title</a></li>
                <li><a href="#">title</a></li>
            </ul>
        </li>
        <!--endnoindex-->

        <li class="xc"><a href="#">Sexual harassment</a>
            <ul id="Sexual harassment">
                <li><a href="#">title</a></li>
                <li><a href="#">title</a></li>
            </ul>
        </li>
        <!--endnoindex-->





        <li class="xc"><a href="#">Discrimination</a>
            <ul id="Discrimination">
                <li><a href="#">title</a></li>
                <li><a href="#">title</a></li>
            </ul>
        </li>
        <!--endnoindex-->
        <li class="xc"><a href="#">Managing complaints</a>
            <ul id="Managing complaints">
                <li><a href="#">title</a></li>
                <li><a href="#">title</a></li>
            </ul>
        </li>
        <!--endnoindex-->


        <li class="xc"><a href="#">Absenteeism</a>
            <ul id="Absenteeism">
                <li><a href="#">title</a></li>
                <li><a href="#">title</a></li>


            </ul>
        </li>
        <!--endnoindex-->
        <li class="xc"><a href="#">Suspension</a>
            <ul id="Suspension">
                <li><a href="#">title</a></li>
                <li><a href="#">title</a></li>


            </ul>
        </li>
        <!--endnoindex-->
        <li class="xc"><a href="#">Discipline</a>
            <ul id="Discipline">
                <li><a href="#">title</a></li>
                <li><a href="#">title</a></li>


            </ul>
        </li>
        <!--endnoindex-->
        <li class="xc"><a href="#">Ill health issues</a>
            <ul id="Ill health issues">
                <li><a href="#">title</a></li>
                <li><a href="#">title</a></li>


            </ul>
        </li>
        <!--endnoindex-->
        <li class="xc"><a href="#">Flexible work arrangements</a>
            <ul id="Flexible work arrangements">
                <li><a href="#">title</a></li>
                <li><a href="#">title</a></li>
                <li><a href="#">title</a></li>

            </ul>
        </li>
        <!--endnoindex-->

        <li class="xc"><a href="#">myHR</a>
            <ul id="myHR">
                <li><a href="#">title</a></li>
                <li><a href="#">title</a></li>
                <li><a href="#">title</a></li>

            </ul>
        </li>
        <!--endnoindex-->

        <li></li>
        <!--blank spacer. needed as QHEPS shell table styles conflict with custom styles here -->
    </ul>
</div>
