<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">

            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="#" title="spare">spare</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="#" title="spare">spare</a></li>

        </ul>
    </div>
    <h3 class="sidebar">Supporting resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/policies-agreements-directives/policy-index/" title="HR policy index">HR policy index</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="http://qheps.health.qld.gov.au/hr/policies-agreements-directives/delegations/home.htm" title="Delegations">Delegations</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="#" title="spare">spare</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="#" title="spare">spare</a></li>

        </ul>
    </div>
</div>
<!-- END Quick Links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <!-- Customise with the sub-site's direct email contact -->
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><a href="mailto:#" title="Email"><span style="color: #ff0000;"> Email and/or phone?</span></a>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->
