<h2>Mentors</h2>
<p>Ever thought about becoming a mentor but wasn't sure it was for you?</p>
<p>Watch these two videos to gain insights, from mentors across the department, on why you might want to consider investing your time in becoming a mentor.</p>
<div class="row clearfix">
    <div class="col-1-3">
        <h3>The why</h3>
        <iframe src="https://player.vimeo.com/video/220735932" width="256" height="144" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        <p class="figcaption">The why (1mins, 20secs)
            <br>
            <a href="/hr/mentoring/docs/video-transcript-mentors-1.pdf">Video transcript</a> (PDF, 214kB)</p>
    </div>
    <div class="col-1-3">
        <h3>What's in it for you?</h3>
        <iframe src="https://player.vimeo.com/video/220737566" width="256" height="144" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        <p class="figcaption">What's in it for you? (47secs)
            <br>
            <a href="/hr/mentoring/docs/video-transcript-mentors-2.pdf">Video transcript</a> (PDF, 207kB)</p>
    </div>
</div>
<h2>Mentees</h2>
<p>Not sure what mentoring is or how you can benefit?</p>
<p>Here are four short videos from department employees &ndash; talking about their experiences, the process and what you might expect. They provide information to help you decide whether you might benefit from having a mentor.</p>
<div class="row clearfix">
    <div class="col-1-3">
        <h3>What drove me to want a mentor</h3>
        <iframe src="https://player.vimeo.com/video/221677783" width="256" height="144" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        <p class="figcaption">What drove me to want a mentor (1mins, 8secs)
            <br>
            <a href="/hr/mentoring/docs/video-transcript-mentees-1.pdf">Video transcript</a> (PDF, 214kB)</p>
    </div>
    <div class="col-1-3">
        <h3>What are the benefits?</h3>
        <iframe src="https://player.vimeo.com/video/221679380" width="256" height="144" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        <p class="figcaption">What are the benefits? (1mins, 24secs)
            <br>
            <a href="/hr/mentoring/docs/video-transcript-mentees-2.pdf">Video transcript</a> (PDF, 214kB)</p>
    </div>
    <div class="col-1-3">
        <h3>The first meeting</h3>
        <iframe src="https://player.vimeo.com/video/221677855" width="256" height="144" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        <p class="figcaption">The first meeting (1mins, 30secs)
            <br>
            <a href="/hr/mentoring/docs/video-transcript-mentees-3.pdf">Video transcript</a> (PDF, 214kB)</p>
    </div>
    <div class="col-1-3">
        <h3>Real life outcomes</h3>
        <iframe src="https://player.vimeo.com/video/221677973" width="256" height="144" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        <p class="figcaption">Real life outcomes (1mins, 4secs)
            <br>
            <a href="/hr/mentoring/docs/video-transcript-mentees-4.pdf">Video transcript</a> (PDF, 208kB)</p>
    </div>
</div>