<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Quick Links section-->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i>
                <a href="/hr/learning/training-calendar.htm">Training calendar</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i>
                <a href="/hsq-staff/hr/training/mentoring-program.htm">HSQ Mentoring program</a></li>
        </ul>
    </div>
</div>
<!--END Quick Links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><strong><a href="mailto:MentorME@health.qld.gov.au">Email us</a></strong>
                <!-- Customise with sub-site contact's direct email -->
            </li>
            <li>
                <!-- Customise with the sub-site's direct email contact -->
                <i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.yammer.com/health.qld.gov.au/#/threads/inGroup?type=in_group&feedId=4713761">Join our Leadership Development group on Yammer</a>
            </li>
            <li>
                <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="/hr/contact/local-hr-contacts.htm">Contact your local HR</a></strong>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->