<div style="width:100%; min-height:0;" class="box-feature">
    <div class="hr-form hr-search">
        <script type="text/javascript" src="http://qheps.health.qld.gov.au/_includes/scripts/funnelback.js"></script>
        <form action="javascript: fbsearch('p-search','qheps.health.qld.gov.au/hr/policies-agreements-directives/policy-index');" name="p-search">
            <input name="query" class="query" size="25" type="text" placeholder="Type keywords(s) to limit your search to HR policies" />
            <input id="searchbut" type="submit" value="" />
        </form>
    </div>
</div>