<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->

<!-- BEGIN Quick Links section -->
<!-- <div class="sidebar_section">
    <h3 class="sidebar">Additional information</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://www.health.qld.gov.au/directives/employment/">Health employment directives</a></li>
        </ul>
    </div>
</div> -->
<!-- END Quick Links section -->

<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><strong><a href="mailto:employmentarrangements@health.qld.gov.au">email us</a></strong>
                <!-- Customise with sub-site contact's direct email -->
            </li>
            <li>
              <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="/hr/contact/local-hr-contacts.htm">Contact your local HR</a></strong>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->
