<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->

<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Supporting resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="https://www.forgov.qld.gov.au/legislation-public-service">Public Service Act 2008</a></li>
            <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="https://apps.legislation.qld.gov.au/Search/isysquery/b0154526-f2e3-4938-b900-d4f739d28844/7/doc/HHNA11.pdf#xml=https://www.legislation.qld.gov.au/Search/isysquery/b0154526-f2e3-4938-b900-d4f739d28844/7/hilite/">Hospital and Health Boards Act 2011</a></li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="https://www.forgov.qld.gov.au/documents/guideline/best-practice-guide-executive-recruitment-and-selection">PSC's Best practice guide for executive recruitment and selection</a> (PDF, 498KB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="hr/executives/performance.htm">Performance plans and agreemenmts</a></li>
        </ul>
    </div>
</div>
<!-- END Quick Links section -->

<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="https://www.qld.gov.au/about/how-government-works/government-structure/public-service-commission">Public Service Commission</a></li>
            <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="https://apps.legislation.qld.gov.au/Search/isysquery/b0154526-f2e3-4938-b900-d4f739d28844/7/doc/HHNA11.pdf#xml=https://www.legislation.qld.gov.au/Search/isysquery/b0154526-f2e3-4938-b900-d4f739d28844/7/hilite/">Hospital and Health Boards Act 2011</a></li>
            <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="/hr/pay-leave-benefits/wage-rates/home.htm">Wage rates</a></li>
            <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/system-governance/policies-standards">Queensland Health policies and standards</a></li>
            <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="https://www.forgov.qld.gov.au/directives-policies-and-guidelines">Public Service Commission directives</a></li>
        </ul>
    </div>
</div>
<!-- END Quick Links section -->

<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
              <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="/hr/contact/local-hr-contacts.htm">Contact your local HR</a></strong>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->
