<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Previous circulars</h3>
    <div class="quick_links">
        <p>
            <a href="/hr/circulars/2016/home.htm">2016</a> |
            <a href="/hr/circulars/2015/home.htm">2015</a> |
            <a href="/peopleandculture/circulars/circular_14.htm">2014</a> |
            <a href="/peopleandculture/circulars/circular_13.htm">2016</a> |
            <a href="/peopleandculture/circulars/circular_12.htm">2013</a> |
            <a href="/peopleandculture/circulars/circular_12.htm">2012</a> |
            <a href="/peopleandculture/circulars/circular_11.htm">2011</a> |
            <a href="/peopleandculture/circulars/circular_10.htm">2010</a> |
            <a href="/peopleandculture/circulars/circular_09.htm">2009</a> |
            <a href="/peopleandculture/circulars/circular_08.htm">2008</a> |
            <a href="/peopleandculture/circulars/2007/circulars_07.htm">2007</a> |
            <a href="/peopleandculture/circulars/2006/hr_circulars_2006.htm">2006</a> |
            <a href="/peopleandculture/circulars/2005/hr_circulars_2005.htm">2005</a> |
            <a href="/peopleandculture/circulars/2004/circulars_2004.htm">2004</a> |
            <a href="/peopleandculture/circulars/2003/2003_circulars.htm">2003</a> |
            <a href="/peopleandculture/circulars/2002/circular_2002.htm">2002</a> |
            <a href="/peopleandculture/circulars/2001/circulars_2001.htm">2001</a> |
            <a href="/peopleandculture/circulars/2000/circulars_2000.htm">2000</a> |
            <a href="/peopleandculture/circulars/1999/circulars_1999.htm">1999</a>
        </p>
    </div>
    <p>Please contact us if you require access to a circular that is not linked here.</p>
</div>
<!-- END Quick Links section -->
<!-- BEGIN Related Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.health.qld.gov.au/directives/employment/">Health employment directives</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/circulars/">HR circulars</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/employment-conditions/policies/irm-index.htm">IRMs (Integrated Resource Manuals)</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.health.qld.gov.au/directives/html/a.asp">Health service directives</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/pay-leave-benefits/wage-rates/home.htm">Wage rates</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.health.qld.gov.au/qhpolicy/html/index-a.asp">A&ndash;Z of all Queensland Health policies</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.forgov.qld.gov.au/directives-policies-and-guidelines">Public Service Commission directives</a></li>
        </ul>
    </div>
</div>
<!-- END Related Links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><strong><a href="mailto:employmentarrangements@health.qld.gov.au">email us</a></strong>
                <!-- Customise with sub-site contact's direct email -->
            </li>
            <li>
                <!-- Customise with the sub-site's direct email contact -->
                <i class="fa-li fa fa-phone fa-lg" aria-hidden="true"></i><strong>Call us:</strong> <a href="tel:0732247090" class="tel">(07) 3234 0934</a>
            </li>
            <li>
                <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="/hr/contact/local-hr-contacts.htm">Contact your local HR</a></strong>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->