<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->

<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
  <h3 class="sidebar">Additional information</h3>
  <div class="quick_links">
    <ul class="fa-ul">
        <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/system-governance/policies-standards/doh-policy/policy/qh-pol-202.pdf">Public Interest Disclosures HR Policy I5</a> (PDF, 280kB)</li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://elearn.com.au/qh/START.htm">Public Interest Disclosures online learning tool</a></li>
    </ul>
  </div>
</div>
<!-- END Quick Links section -->

<!-- BEGIN Contact section -->
<div class="sidebar_section">
  <h3 class="sidebar">Contact us</h3>
  <div class="quick_links">
    <p><strong>Ethical Standards Unit</strong></p>
    <ul class="fa-ul">
      <li>
        <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><strong><a href="mailto:co_complaints@health.qld.gov.au">email us</a></strong>
        <!-- Customise with sub-site contact's direct email -->
      </li>
      <li>
        <!-- Customise with the sub-site's direct email contact -->
        <i class="fa-li fa fa-phone fa-lg" aria-hidden="true"></i>Phone: (07) 3405 5771</a>
      </li>
    </ul>
  </div>
</div>
<!-- END Contact section -->
