<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Free resources for staff &amp; family</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i>Simply log on to <a href="https://www.livewell.optum.com/public/welcome.asp">Livewell</a> and enter 'Queensland' as the access code. Start benefiting from a wide range of fact sheets, 5 step programs and information to prepare you for the challenges of everyday life.</li>
        </ul>
    </div>
</div>
<!-- END Quick Links section -->
<!-- BEGIN Supporting resources section -->
<div class="sidebar_section">
    <h3 class="sidebar">Supporting resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/staff-health-wellbeing/counselling-support/docs/manager-resource-guide.pdf">Manager's resource guide</a> (PDF, 3.6MB)</li>
            <h4>Promotional material</h4>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/staff-health-wellbeing/counselling-support/docs/eap-poster.pdf">A4 poster</a> (PDF, 950KB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/staff-health-wellbeing/counselling-support/docs/ea-brochure.pdf">Brochure</a> (PDF, 2.5MB)</li>
        </ul>
    </div>
</div>
<!-- END Supporting resources section -->
<!-- BEGIN Related Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-question-circle fa-lg" aria-hidden="true"></i><a href="/hr/staff-health-wellbeing/counselling-support/faqs-eap.htm">FAQs</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/staff-wellness/home.htm">Staff wellness</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.beyondblue.org.au/home">Beyond Blue</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.blackdoginstitute.org.au/">Black Dog Institute</a></li>
        </ul>
    </div>
</div>
<!-- END Related Links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><a href="http://qheps.health.qld.gov.au/hr/contacts/whs.htm">OHS contacts</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><strong><a href="https://www.livewell.optum.com/public/welcome.asp?timeout=1">OPTUM</a></strong>
                <br>(enter 'Queensland' as the access code)</li>
            <li><i class="fa-li fa fa-phone fa-lg" aria-hidden="true"></i><strong>Call OPTUM:</strong> 1800 604 640 (toll free)</li>
        </ul>
    </div>
</div>
<!-- END Contact section -->