<style type="text/css"><!--
#contentblock30 {border: 0px;}
.blue h3{color: #fff;}
.purple h3{color: #fff;}
.four-boxes h1{color: #fff; font-size: 18px;}
.four-boxes a{color: #fff;}
table.right-column {border-radius: 4px; background: #fafafa; width: 100%; border: 1px solid #ededed; padding: 15px;}
.right-column td{padding: 3; border-radius: 5px;}
.right-column .heading{font-size: 14px; font-weight: bold; background: #1b75bb; width: 100%;color: #fff; padding: 6 5 6 5;}
.right-column ul li {margin: 2px 0;text-align: left; font-size: 1em; color: #3399cc;}

table.right-column img {width: inherit; width: 100%; width:auto; -ms-interpolation-mode: bicubic;}

.purple{background: #92809B;border-radius: 5px;padding: 20px;}
.blue{background: #1b75bb;border-radius: 5px;padding: 20px;}
.green{background: #9BBB59;border-radius: 5px;padding: 20px;}
.teal{background: #5CB37C;border-radius: 5px;padding: 20px;}
.grey{background: #ededed;border: 1px solid #ccc;border-radius: 5px;padding: 10px;}
.light-blue{background: #a2d2e0;border-radius: 5px;}
.light-grey{padding: 10px;background: #fafafa ;border-radius: 5px; border: 1px solid #ededed;}
.light-grey a{color: #3399cc;}
td.light-blue, td.purple, td.blue, td.green, td.teal{padding: 8px; color: #fff;border: 0px; }

.hrs-button{border-radius: 5px; text-align: center; border: 1px solid #ededed;padding: 14px;width: 22%;box-shadow: 2px 2px 2px #ccc;}
.hrs-button a{text-decoration: none;}

.front-boxes td{ border-radius: 5px; border: 1px solid #ccc; padding: 8px;width: 30%;}
.four-boxes td{border-radius: 5px;width: 22%; text-align: center;}
--></style>


#nav2 { 
width: 250px; 
margin: 17 0 15px 15px; 
padding: 0 0 0 0;
background: #fafafa;
border: 1px solid #ededed; 
border-radius: 5px;
/*-z-index: 1;*/
}
#nav2 ul {
padding: 0.9em 0 0 2.3em;
}

#nav2 ul li {
margin-bottom: 0.6em;
}

#nav2 ul li.xc {
padding-bottom:0.6em;
margin-bottom:0;
}