<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->

<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
  <h3 class="sidebar">Tools and resources</h3>
  <div class="quick_links">
    <ul class="fa-ul">
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="/hr/recruitforfit/process/role-description-templates.htm" title="Role description template">Role description templates</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="https://smartjobs.qld.gov.au/jobtools/!v4nav.go?acti=12000&orgi=15137&hash=DCC319D60B95FB02&in_token=Y" title="Request to hire">Request to hire</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://qheps.health.qld.gov.au/hr/recruitforfit/docs/Telephone-screen-template.doc" title="Telephone screen template">Telephone screen template</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://qheps.health.qld.gov.au/hr/recruitforfit/docs/Interview-guide-template.docx" title="Interview Guide">Interview guide template</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://qheps.health.qld.gov.au/hr/recruitforfit/docs/Referee-check-template.doc" title="Referee check template">Referee check template</a></li>
    </ul>
  </div>
</div>
<!-- END Quick Links section -->

<!-- BEGIN Contact section -->
<div class="sidebar_section">
  <h3 class="sidebar">Need more help?</h3>
  <div class="quick_links">
    <ul class="fa-ul">
      <li>
        <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><strong><a href="/hr/recruitforfit/contact/home.htm">Contact us</a></strong>
        <!-- Customise with sub-site contact's direct email -->
      </li>
      <li>
        <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="/hr/contact/local-hr-contacts.htm">Contact your local HR</a></strong>
      </li>
    </ul>
  </div>
</div>
<!-- END Contact section -->
