<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Related Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/staff-wellness/corporate-discounts/home.htm" title="Corporate discounts">Corporate discounts</a></li>
            <!--         <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/staff-wellness/week/home.htm">2016 Staff Wellness week</a></li>
			-->
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://workplaces.healthier.qld.gov.au/"><span style="font-weight:bolder;">Healthier. Happier.</span> Workplaces</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.healthier.qld.gov.au/"><span style="font-weight:bolder;">Healthier. Happier.</span></a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.amaq.com.au/page/Advocacy/ama-queensland-resilience-on-the-run-program/"><span style="font-weight:bolder;">Resilience on the run program</span></a></li>
        </ul>
    </div>
</div>
<!-- END Related Links section -->
<!-- <div class="promo-image"><a href="https://www.qldmentalhealthweek.org.au/"><img src="/hr/staff-health-wellbeing/staff-wellbeing/images/2017-qld-mental-health-week.jpg" alt="Queensland Mental Heal. 8-14 October 2017"></a></div> -->
<!-- BEGIN Supporting resources section -->
<div class="sidebar_section">
    <h3 class="sidebar">Supporting resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/staff-health-wellbeing/staff-wellbeing/docs/mental-health-framework-2017.pdf">Workplace Mental Health and Wellbeing Framework</a> (PDF, 323kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/staff-health-wellbeing/staff-wellbeing/docs/early-intervention-factsheet.pdf">Early intervention program factsheet</a> (PDF, 372kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/staff-health-wellbeing/staff-wellbeing/docs/early-intervention-program.pdf">Early intervention program overview</a> (PDF, 191kB)</li>
            <li><i class="fa-li fa fa-file-word-o fa-lg" aria-hidden="true"></i><a href="/hr/staff-health-wellbeing/staff-wellbeing/docs/Identifying-psychosocial-hazards.docx">Identifying-psychosocial-hazards</a> (DOC, 180kB)</li>
        </ul>
    </div>
</div>
<!-- END Supporting resources section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <!-- Customise with the sub-site's direct email contact -->
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><a href="mailto:OHS@health.qld.gov.au" title="Email the Safety and wellbeing team">Email Safety &amp; wellbeing team</a>
            </li>
            <li>
                <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="/hr/contact/local-hr-contacts.htm">Contact your local HR</a></strong>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->