<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Supporting resources section -->
<div class="sidebar_section">
    <h3 class="sidebar">Supporting resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/docs/policies-agreements-directives/eb9-workload-management-kit.pdf">EB9 workforce workload management kit</a> (PDF, 950kB)</li>
        </ul>
    </div>
</div>
<!-- END Supporting resources section -->
<!-- BEGIN Related Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.health.qld.gov.au/employment/conditions/contracts/medical/default.asp">Visiting medical officers contracts</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/peopleandculture/exec_policy/home.htm">Executive and senior officer employment</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/pay-leave-benefits/wage-rates/home.htm">Wage rates</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.health.qld.gov.au/employment/conditions/awards-agreements/industrial-framework/default.asp">Industrial relations framework</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.elearn.com.au/qh_contractor/">Contractor induction</a>&nbsp; (elearn)</li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/safety/hazards/chemalert.htm">Chemalert</a>&nbsp;</li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/safety/safety_topics/sms_guides.htm">Safety management system</a> </li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/safety/hazards/chemalert.htm">Hazardous materials management using ChemAlert</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/safety/hazards/chemalert6.htm">Navigating ChemAlert to compile a HazMat register</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.legislation.qld.gov.au/OQPChome.htm">Queensland legislation</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.abcb.gov.au/">Australian Building Code</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.dsdip.qld.gov.au">Department of State Development, Infrastructure and&nbsp;Planning</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.justice.qld.gov.au">Department of Justice and Electrical Safety</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.standards.org.au/Pages/default.aspx">Standards Australia</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://secure.publicworks.qld.gov.au/bemir/Login.aspx">Built Environment Material Information Register (BEMIR)</a> (login / password&nbsp;required) </li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://australia.gov.au/topics/environment-and-natural-resources/energy/energy-efficiency">Energy Efficiency</a> </li>
        </ul>
    </div>
</div>
<!-- END Related Links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><strong><a href="mailto:HRConnect@health.qld.gov.au">Email HR Connect</a></strong>
                <!-- Customise with sub-site contact's direct email -->
            </li>
            <li>
                <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="/hr/contact/local-hr-contacts.htm">Contact your local HR</a></strong>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->