<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Supporting resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.forgov.qld.gov.au/documents/directive/1513/recruitment-and-selection">Directive 15/13</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/policies-agreements-directives/policy-index/b-resourcing/recruitment-and-selection.htm">HR policy B41 Recruitment and Selection</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.forgov.qld.gov.au/documents/guideline/best-practice-guide-executive-recruitment-and-selection">PSC's Best practice guide for executive recruitment and selection</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/executives/performance.htm">Performance plans and agreemenmts</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/onboarding/executives/home.htm">Onboarding new executives</a></li>
        </ul>
    </div>
</div>
<!-- END Quick Links section -->
<!-- BEGIN Related Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/executives/home.htm">Executive portal</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/executives/delegations.htm">Delegations</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/pay-leave-benefits/wage-rates/home.htm">Wage rates</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/system-governance/policies-standards">Queensland Health policies and standards</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.forgov.qld.gov.au/directives-policies-and-guidelines">Public Service Commission directives</a></li>
        </ul>
    </div>
</div>
<!-- END Related Links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="https://www.health.qld.gov.au/employment/job-search/hhs-recruitment-contact">Contact your local recruitmemt team</a></strong>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->