<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Latest policy updates and memos</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/circulars/2017/hr-05-17.pdf">HR Circular 05/17 Implementation of the Bus Travel Benefit item</a> (PDF, 188KB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/circulars/2017/hr-04-17.pdf">HR Circular 04/17 Amendments to HR policy</a> (PDF, 208KB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/circulars/2017/hr-03-17.pdf">HR Circular 03/17 Amendments to HR policy</a> (PDF, 203KB)</li>
        </ul>
    </div>
</div>
<!-- END Quick Links section -->
<!-- BEGIN Related Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/employment-conditions/policies/irm-index.htm">IRMs (Integrated Resource Manuals)</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.health.qld.gov.au/directives/html/a.asp">Health service directives</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/pay-leave-benefits/wage-rates/home.htm">Wage rates</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/system-governance/policies-standards">Queensland Health policies and standards</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.forgov.qld.gov.au/directives-policies-and-guidelines">Public Service Commission directives</a></li>
        </ul>
    </div>
</div>
<!-- END Related Links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="/hr/contact/local-hr-contacts.htm">Contact your local HR</a></strong>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->