<!-- Customise the sidebar links below as appropriate -->
<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Supporting resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="http://www.psc.qld.gov.au/publications/directives/assets/2014-10-CCE-Critical-Incident-Response-and-Recovery.docx">Directive 10/14 &ndash; Critical Incident Response and Recovery</a>&nbsp;(PDF, 252kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="https://www.qld.gov.au/gov/documents/directive/0616/critical-incident-entitlements-and-conditions">Directive 06/16 &ndash; Critical Incident Entitlements</a>&nbsp;(PDF, 256kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/crrr/docs/crrr-info-sheet.pdf">Information for nominees and their line managers</a> (PDF, 69kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/crrr/docs/flyer.pdf">General information - Flyer</a> (PDF, 68kB)</li>
        </ul>
    </div>
</div>
<!-- END Quick Links section -->
<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://communities.govnet.qld.gov.au/comgovnet/the-new-community-recovery-ready-reserve">Department of Communities, Child Safety and Disability Services (DCCSDS)</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://getready.qld.gov.au/">Queensland Government &ndash; Get Ready Queensland</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.bom.gov.au/">Bureau of Meteorology</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/staff-health-wellbeing/counselling-support/home.htm">Employee assistance</a></li>
        </ul>
    </div>
</div>
<!-- END Quick Links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <!-- Customise with sub-site contact's direct email -->
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><a href="mailto:ready.reserve@health.qld.gov.au">Email Ready reserve</a>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->