<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Supporting resources section -->
<!--<div class="sidebar_section">
  <h3 class="sidebar">Supporting resources</h3>
  <div class="quick_links">
    <ul class="fa-ul">
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="https://www.communities.qld.gov.au/gateway/end-domestic-and-family-violence">Ending domestic and family violence</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="https://www.qld.gov.au/gov/domestic-and-family-violence">Public Service Commission resources</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="https://www.qld.gov.au/community/getting-support-health-social-issue/dfv-read-report-recommendation/index.html">Government reports and recommendations</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://www.whiteribbon.org.au/">White Ribbon Australia</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://ceochallengeaustralia.org/">Australia's CEO Challenge</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="https://www.griffith.edu.au/domestic-family-violence">Griffith University</a></li>
    </ul>
  </div>
</div>-->
<!-- END Supporting resources section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="mailto:Alexis.Stephens@health.qld.gov.au">Email Alexis Stephens</a></strong>
            </li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/staff-health-wellbeing/domestic-family-violence/home.htm">Domestic and family violence</a></li>
        </ul>
    </div>
</div>
<!-- END Contact section -->