<!-- BEGIN Related links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="http://qheps-dev.dctuat.health.qld.gov.au/hr/online/web-design-guide.htm">HR Web design guide</a></li>
            <li>
                <i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="/hr/online/orphans.htm" style="color:#fff;">orphans don't touch!</a></li>
        </ul>
    </div>
</div>
<!-- END Related links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><strong><a href="mailto:HRSOnline@health.qld.gov.au">email HRS Online</a></strong>
                <!-- Customise with sub-site contact's direct email -->
            </li>
            <li>
                <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="/hr/contact/local-hr-contacts.htm">Contact your local HR</a></strong>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->