<!-- This stylesheet is for custom styles and colours specific to your current sub-site only. Please use /hr/include/css.inc for global HR styles. -->

<!-- Data tables -->
<style>
    table.data {
        border-collapse: collapse;
        width: 100%;
        border-bottom: 3px solid #8bcfb3;
    }

    table.data th {
        background-color: #8bcfb3;
        height: 40px;
        padding-left: 5px;
    }

    table.data th,
    table.data td {
        padding: 0.25rem;
    }

    table.data tr {
        border-bottom: 1px solid #8bcfb3;
    }

    table.data caption {
        font-size: 75%;
        text-align: left;
        caption-side: bottom;
    }

    table.data h2 {
      color: #0076BD;
      font-size: 130%;
    }

    table.data h3 {
      color: #0D4E95;
      font-size: 115%;
    }
</style>
