<!-- BEGIN Quick Links section -->
<div>
  <h3 class="shortcuts">Supporting resources</h3>
</div>
<div>
  <div id="quick_links">
    <ul class="quick_links">
      <li class="icon_bullet"><a href="/hr/diversity-inclusion/supporting-resources.htm#pl">Policies &amp; legislation</a></li>
      <li class="icon_bullet"><a href="/hr/diversity-inclusion/supporting-resources.htm#fr">Further reading</a></li>
    </ul>
  </div>
</div>
<!-- END Quick Links section -->

<!-- BEGIN Quick Links section -->
<div>
  <h3 class="shortcuts">External links</h3>
</div>
<div>
  <div id="quick_links">
    <ul class="quick_links">
      <li class="icon_bullet"><a href="http://qheps.health.qld.gov.au/eap/home.htm">Employee Assistance Program</a></li>
      <li class="icon_bullet"><a href="https://www.adcq.qld.gov.au/">Anti-Discrimination Commission Queensland</a></li>
      <li class="icon_bullet"><a href="https://www.dca.org.au/">Diversity Council Australia</a></li>
      <li class="icon_bullet"><a href="https://www.wgea.gov.au/">Workplace Gender Equality Agency</a></li>
      <li class="icon_bullet"><a href="https://www.humanrights.gov.au/">Australian Human Rights Commission</a></li>
    </ul>
  </div>
</div>
<!-- END Quick Links section -->

<!-- BEGIN Feedback section -->
<div>
  <h3 class="feedback">Need more help?</h3>
</div>
<div>
  <div id="quick_links">
    <ul class="quick_links">
      <li class="icon_email">
        <strong><a href="mailto:diversity.inclusion@health.qld.gov.au">email us</a></strong>
        <!-- Customise with sub-site contact's direct email -->
      </li>
      <li class="icon_contacts">
        <strong><a href="/hr/contact/local-hr-contacts.htm">Contact your local HR</a></strong>
      </li>
    </ul>
  </div>
</div>
<!-- END Feedback section -->
