<div id="hrs_right_column_shadow">
    <div id="rightcolumn">
        <!--#include virtual="/hr/include/css.inc" --> <!-- Global HR stylesheet -->
        <!--#include virtual="/hr/include/search_hr.inc" --> <!-- differing HR subpages search -->

        <!-- UPDATE the following URLs to current sub-site:
              * change folder name after /hr/
              * create an includes folder in it if not already present
              * make copies of below files and customise styles and links as needed -->

        <!--#include virtual="/hr/diversity-inclusion/includes/css_subsite.inc" --> <!-- custom sub-site styles -->
        <!--#include virtual="/hr/diversity-inclusion/includes/quick_links.inc" --> <!-- custom sub-site quicklinks -->
    </div>
</div>
