<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Related links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://vaccinate.initiatives.qld.gov.au/">Vaccination matters</a> </li>
            <li>
                <i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.qld.gov.au/health/conditions/immunisation/benefits/index.html">Benefits of vaccination</a> </li>
            <li>
                <i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.immunise.health.gov.au/">Immunise Australia program</a> </li>
            <li>
                <i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.immunise.health.gov.au/internet/immunise/publishing.nsf/Content/Handbook10-home" title="The Australian Immunisation Handbook 10th Edition">The Australian Immunisation Handbook 10th Edition</a> </li>
            <li>
                <i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.safetyandquality.gov.au/publications/national-safety-and-quality-health-service-standards/" title="National Safety and Quality Health Service Standards">National Safety and Quality Health Service Standards</a> </li>
            <li>
                <i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.nhmrc.gov.au/guidelines-publications/cd33" title="Australian Guidelines for the prevention and control of infection in healthcare">Australian guidelines for the prevention and control of infection in healthcare</a> </li>
        </ul>
    </div>
</div>
<!-- END Related links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <!-- Customise with the sub-site's direct email contact -->
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><strong><a href="mailto:HRconnect@health.qld.gov.au" title="Contact HRconnect">email HRconnect</a></strong>
            </li>
            <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i>The Recruiting Manager listed within the role description </li>
            <li>
                <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong>Contact your local <a href="https://www.health.qld.gov.au/employment/job-search/hhs-recruitment-contact/default.asp">Recruitment Team</a></strong>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->