<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Supporting resources section -->
<div class="sidebar_section">
    <h3 class="sidebar">Supporting resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/publications/employment/work-for-us/dept-of-health/information-sheet-contractors.pdf">Contractors and agency staff</a> (PDF, 105KB)</li>
            <li>
                <i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/publications/employment/work-for-us/dept-of-health/information-sheet-edu-providers.pdf">Education providers</a> (PDF, 78KB)</li>
            <li>
                <i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/staff-vaccinations/docs/information-sheet-procurement-staff.pdf">Procurement staff</a> (PDF, 54KB)</li>
            <li>
                <i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/publications/employment/work-for-us/dept-of-health/information-sheet-student-placements.pdf">Student placements</a> (PDF, 111KB)</li>
            <li>
                <i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/publications/employment/work-for-us/dept-of-health/information-sheet-volunteers.pdf">Volunteers</a> (PDF, 103KB)</li>
        </ul>
    </div>
</div>
<!-- END Supporting resources section -->
<!-- BEGIN Related links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/employment/work-for-us/dept-of-health/pre-employment/vaccinations/conditions/default.asp">Vaccinations as a condition of employment</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/employment/work-for-us/dept-of-health/pre-employment/vaccinations/risk-roles/default.asp">Vaccine preventable disease risk roles</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/employment/work-for-us/dept-of-health/pre-employment/vaccinations/specified-diseases/default.asp">Specified vaccine preventable diseases</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/employment/work-for-us/dept-of-health/pre-employment/vaccinations/providing-evidence/default.asp">Providing evidence of vacination</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/system-governance/policies-standards/doh-policy/policy/qh-pol-212.pdf">HR Policy B1 - Recruitment and Selection</a> &ndash; Section 13.7</li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/directives/employment/hed-0116.pdf" title="HED 01/16, Health Employment Directive">Health Employment Directive 01/16</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.immunise.health.gov.au/internet/immunise/publishing.nsf/Content/Handbook10-home">The Australian Immunisation Handbook 10<sup>th</sup> Edition</a></li>
            <li>
                <i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://vaccinate.initiatives.qld.gov.au/">Vaccination matters</a> </li>
            <li>
                <i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.qld.gov.au/health/conditions/immunisation/benefits/index.html">Benefits of vaccination</a> </li>
            <li>
                <i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.immunise.health.gov.au/">Immunise Australia program</a> </li>
            <li>
                <i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.safetyandquality.gov.au/publications/national-safety-and-quality-health-service-standards/">National Safety and Quality Health Service Standards</a> </li>
            <li>
                <i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.nhmrc.gov.au/guidelines-publications/cd33">Australian guidelines for the prevention and control of infection in healthcare</a> </li>
        </ul>
    </div>
</div>
<!-- END Related links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <!-- Customise with the sub-site's direct email contact -->
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><strong><a href="mailto:HRconnect@health.qld.gov.au" title="Contact HRconnect">email HRconnect</a></strong>
            </li>
            <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i>The Recruiting Manager listed within the role description </li>
            <li>
                <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong>Contact your local <a href="https://www.health.qld.gov.au/employment/job-search/hhs-recruitment-contact/default.asp">Recruitment Team</a></strong>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->