<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Supporting resources section -->
<div class="sidebar_section">
    <h3 class="sidebar">Supporting resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/staff-vaccinations/docs/flu-consent-form-2017.pdf">Vaccination consent form 2017</a> (PDF, 497KB)</li>
            <li>
                <i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/staff-vaccinations/docs/flu-faqs-2017.pdf">FAQs for 2017 flu vaccination</a> (PDF, 1.2MB)</li>
            <li>
                <i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/staff-vaccinations/docs/fluquadri-consumer-information.pdf">FluQuadri consumer medicine information</a> (PDF, 20KB)</li>
        </ul>
    </div>
</div>
<!-- END Supporting resources section -->
<!-- BEGIN Related links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/clinical-practice/guidelines-procedures/diseases-infection/diseases/influenza/resources">Flu prevention resources</a></li>
            <li>
                <i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://conditions.health.qld.gov.au/HealthCondition/condition/8/118/82/influenza-the-flu">About Inluenza (The Flu)</a></li>
        </ul>
    </div>
</div>
<!-- END Related links section -->
<!-- BEGIN Contacts section -->
<div class="sidebar_section">
    <h3 class="sidebar">Contact information</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i>QHB and Butterfield St, <a href="mailto:OHS@health.qld.gov.au">Robyn Mackenzie</a></li>
            <li>
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i>Wickham St, <a href="mailto:Gerry.Lafferty@health.qld.gov.au">Gerry Lafferty</a></li>
            <li>
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i>Wickham St, <a href="mailto:Anastasia.Tany@health.qld.gov.au">Anastasia Tan</a></li>
        </ul>
    </div>
</div>
<!-- END Contacts section -->