<!-- BEGIN Related links section -->
<div class="sidebar_section">
  <h3 class="sidebar">Related links</h3>
  <div class="quick_links">
    <ul class="fa-ul">
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="/hr/staff-health-wellbeing/domestic-family-violence/docs/wra-workplace-accreditation.pdf">White Ribbon Accreditation factsheet (PDF, 133KB)</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="https://www.communities.qld.gov.au/gateway/end-domestic-and-family-violence">Ending domestic and family violence</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="https://www.qld.gov.au/gov/domestic-and-family-violence">Public Service Commission resources</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="https://www.qld.gov.au/community/getting-support-health-social-issue/dfv-read-report-recommendation/index.html">Government reports and recommendations</a></li>
    </ul>
  </div>
</div>-->
<!-- END Related links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="mailto:Alexis.Stephens@health.qld.gov.au">Email Alexis Stephens</a></strong>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->