<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Supporting resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true "></i><a href="https://www.health.qld.gov.au/system-governance/strategic-direction/plans/workforce-diversity-inclusion-strategy">QH Strategy 2017-2022</a></li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true "></i><a href="/hr/diversity-inclusion/docs/technical-paper.pdf">QH Technical paper</a></li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true "></i><a href="/hr/diversity-inclusion/docs/action-plan-2017-2018.pdf">DoH Action plan 2017-2018</a></li>
        </ul>
    </div>
</div>
<!-- END Quick Links section -->
<!-- BEGIN Quick Links section -->
<div class="sidebar_section ">
    <h3 class="sidebar ">Related links</h3>
    <div class="quick_links ">
        <ul class="fa-ul ">
            <li><i class="fa-li fa fa-circle fa-sm " aria-hidden="true "></i><a href="/hr/staff-health-wellbeing/counselling-support/home.htm ">Employee Assistance Program</a></li>
            <li><i class="fa-li fa fa-globe fa-lg " aria-hidden="true "></i><a href="https://www.adcq.qld.gov.au/ ">Anti-Discrimination Commission Queensland</a></li>
            <li><i class="fa-li fa fa-globe fa-lg " aria-hidden="true "></i><a href="https://www.dca.org.au/ ">Diversity Council Australia</a></li>
            <li><i class="fa-li fa fa-globe fa-lg " aria-hidden="true "></i><a href="https://www.wgea.gov.au/ ">Workplace Gender Equality Agency</a></li>
            <li><i class="fa-li fa fa-globe fa-lg " aria-hidden="true "></i><a href="https://www.humanrights.gov.au/ ">Australian Human Rights Commission</a></li>
        </ul>
    </div>
</div>
<!-- END Quick Links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section ">
    <h3 class="sidebar ">Need more help?</h3>
    <div class="quick_links ">
        <ul class="fa-ul ">
            <li><i class="fa-li fa fa-envelope fa-lg " aria-hidden="true "></i><a href="mailto:diversity.inclusion@health.qld.gov.au ">Email us</a></li>
            <li><i class="fa-li fa fa-address-book fa-lg " aria-hidden="true "></i><a href="/hr/contacts/local-hr-units.htm ">Contact your local HR</a></li>
        </ul>
    </div>
</div>
<!-- END Contact section -->