<!-- Customise the sidebar links below as appropriate -->

<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
  <h3 class="sidebar">Additional resources</h3>
  <div class="quick_links">
    <ul class="fa-ul">
      <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="/governance/fraud/training.htm">Ethics awareness and fraud control training</a></li>
      <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="/governance/risk/framework.htm">Updated Risk Management Framework</a></li>
      <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/employment/conditions/staff-complaints/how-to/corrupt-conduct/default.asp">Corrupt conduct</a></li>
      <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/employment/conditions/staff-complaints/how-to/public-interest-disclosure/default.asp">Public interest disclosures</a></li>
    </ul>
  </div>
</div>
<!-- END Quick Links section -->

<!-- BEGIN Contact section -->
<div class="sidebar_section">
  <h3 class="sidebar">Need more help?</h3>
  <div class="quick_links">
    <ul class="fa-ul">
      <li>
        <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><strong><a href="mailto:co_complaints@health.qld.gov.au">email us</a></strong>
        <!-- Customise with sub-site contact's direct email -->
      </li>
      <li>
        <!-- Customise with the sub-site's direct email contact -->
        <i class="fa-li fa fa-phone fa-lg" aria-hidden="true"></i>Phone: (07) 3405 5771</a>
      </li>
      <li>
        <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="/hr/contact/local-hr-contacts.htm">Contact your local HR</a></strong>
      </li>
    </ul>
  </div>
</div>
<!-- END Contact section -->
