<!-- Customise the sidebar links below as appropriate -->

<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
  <h3 class="sidebar">Qld Health resources</h3>
  <div class="quick_links">
    <ul class="fa-ul">
      <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/employment/conditions/staff-complaints/get-support/default.asp">Get support</a></li>
      <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/employment/conditions/staff-complaints/how-to/employment/default.asp">Employment complaints</a></li>
      <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/employment/conditions/staff-complaints/how-to/clinical-performance/default.asp">Clinician performance</a></li>
      <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/nonconsumer_complaint/patient.asp">Clinical incidents</a></li>
    </ul>
  </div>
</div>
<!-- END Quick Links section -->

<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
  <h3 class="sidebar">Making a complaint</h3>
  <div class="quick_links">
    <ul class="fa-ul">
      <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i>speak with your&nbsp;line manager</li>
      <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i>get support from your <a href="/hr/contact/local-hr-contacts.htm">local hr unit</a></li>
      <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i>access the <a href="http://qheps.health.qld.gov.au/eap/home.htm">Employee Assistance Program</a>&nbsp;available 24 hours a day, seven days a week, on <a href="tel:1800604640" class="tel">1800 604 640</a>.</li>
    </ul>
  </div>
</div>
<!-- END Quick Links section -->

    <!-- BEGIN Quick Links section -->
    <div class="sidebar_section">
      <h3 class="sidebar">Resources for your workplace</h3>
      <div class="quick_links">
    <ul class="fa-ul">
      <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/employee-complaints/docs/sexual-harassment-poster.pdf">Poster &ndash; Sexual&nbsp;harassment is not ok</a> (PDF, 103KB)</li>
      <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/employee-complaints/docs/sexual-harassment-fs.pdf">Fact sheet &ndash; Sexual harassment</a> (PDF, 128KB)</li>
      <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/system-governance/policies-standards/doh-policy/policy/qh-pol-228.pdf">HR Policy &ndash; Workplace Harassment and Sexual Harassment</a> (PDF, 149KB)</li>
      <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="https://qldhealth.lms.elmolms.com">Online training</a></li>
      <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/employee-complaints/docs/informal-complaints-resolution-guide.pdf">Guide for resolution of informal complaints at the local level</a> (PDF, 594KB)</li>
    </ul>
  </div>
</div>
<!-- END Quick Links section -->

<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
  <h3 class="sidebar">External links</h3>
  <div class="quick_links">
    <ul class="fa-ul">
      <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://www.ombudsman.qld.gov.au/">Queensland Ombudsman</a></li>
      <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://www.cmc.qld.gov.au/">Crime and&nbsp;Corruption Commission</a></li>
      <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://www.qirc.qld.gov.au/">Queensland Industrial Relations Commission</a></li>
    </ul>
  </div>
</div>
<!-- END Quick Links section -->

<!-- BEGIN Contact section -->
<div class="sidebar_section">
  <h3 class="sidebar">Need more help?</h3>
  <div class="quick_links">
    <ul class="fa-ul">
      <li>
        <!-- Customise with sub-site contact's direct email -->
        <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><a href="mailto:StaffCompliants@health.qld.gov.au">Email&nbsp;Employee complaints</a>
      </li>
      <li>
        <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><a href="mailto:co_complaints@health.qld.gov.au">Email Conduct Advisory Service</a>
      </li>
      <li>
        <i class="fa-li fa fa-phone fa-lg" aria-hidden="true"></i>Call <a href="tel:1800195240" class="tel">1800 195 240</a>
      </li>
      <li>
        <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="/hr/contact/local-hr-contacts.htm">Contact your local HR</a></strong>
      </li>
    </ul>
  </div>
</div>
<!-- END Contact section -->
