<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Additional resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="/hr/staff-wellness/corporate-discounts/home.htm" title="Corporate discounts">Corporate discounts</a></li>
            <!--         <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/staff-wellness/week/home.htm">2016 Staff Wellness week</a></li>
 -->
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://workplaces.healthier.qld.gov.au/"><span style="font-weight:bolder;">Healthier. Happier.</span> Workplaces</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="http://www.healthier.qld.gov.au/"><span style="font-weight:bolder;">Healthier. Happier.</span></a></li>
        </ul>
    </div>
</div>
<!-- END Quick Links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <!-- Customise with the sub-site's direct email contact -->
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><a href="mailto:OHS@health.qld.gov.au" title="Email the Safety and wellbeing team">Safety and wellbeing team</a>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->