<!-- Customise the sidebar links below as appropriate -->
<!-- BEGIN Survey results section -->
<!-- <div class="sidebar_section">
  <h3 class="sidebar">Survey results</h3>
  <div class="quick_links">
    <h4>Reports &ndash; 2016</h4>
    <ul class="fa-ul">
      <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/employee-opinion-survey/docs/DOH-highlights-report-2016.pdf" title="DoH key highlights report">2016 DoH key highlights</a> (PDF, 890KB)</li>
      <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/employee-opinion-survey/docs/DOH-cultural-inventory-report-2016.pdf" title="Cultural inventory report 2016">Cultural inventory report</a> (PDF, 223KB)</li>
    </ul>
    <h4>Reports &ndash; 2015 and 2014</h4>
    <ul class="fa-ul">
      <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/employee-opinion-survey/docs/2015-doh-highlights-report.pdf" title="2015 DoH key highlights report">2015 DoH key highlights</a>&nbsp;(PDF, 476KB)</li>
      <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/employee-opinion-survey/docs/2014-doh-highlights-report.pdf" title="2014 DoH key highlights report">2014 DoH key highlights</a>&nbsp;(PDF, 258KB)</li>
    </ul>
  </div>
</div> -->
<!-- END Survey results section -->
<!-- BEGIN Supporting resources section -->
<div class="sidebar_section">
    <h3 class="sidebar">Supporting resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/docs/workplace-culture/2017-wfq-completing-the-survey.pdf">Completing the survey</a> (PDF, 467KB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/docs/workplace-culture/2017-wfq-confidentiality.pdf">Confidentiality (excluding free text)</a> (PDF, 312KB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/docs/workplace-culture/2017-WfQ-pulse-survey-results.pdf">WfQ Pulse survey results</a> (PDF, 139KB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/docs/workplace-culture/workforce-insights-report.pdf">Healthcare workforce insights report</a> (PDF, 1.83KB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/docs/workplace-culture/characteristics-engaged-employees.pdf">Characteristics of an engaged employee</a> (PDF, 242KB)</li>
        </ul>
    </div>
</div>
<!-- END Supporting resources section -->
<!-- BEGIN Related Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.workingforqueensland.com/startlive.asp?vid=QPS999990">Working for Queensland survey</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/culture/home.htm">Our culture</a></li>
        </ul>
    </div>
</div>
<!-- END Related Links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <!-- Customise with sub-site contact's direct email -->
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><a href="/hr/workplace-culture/working-for-queensland-survey/local-survey-coordinators.htm">WfQ local survey coordinators</a>
            </li>
            <li>
                <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="/hr/contacts/local-hr-units.htm">Contact your local HR</a></strong>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->