<div class="css-table" style="width: 500px; margin-bottom:10px;">
    <div class="col" style="height:30px; padding:6px; font-size:1.3em;"><strong>2017</strong></div>
    <div class=" col " style="z-index:0; vertical-align:middle; width: 100%; height: 30px; padding:0; background: #a94442; /* Old browsers */ background: -moz-linear-gradient(left, #a94442 0%, #f7941d 10%, #75c045 100%); /* FF3.6-15 */ background: -webkit-linear-gradient(left, #a94442 0%,#f7941d 10%,#75c045 100%); /* Chrome10-25,Safari5.1-6 */ background: linear-gradient(to right, #a94442 0%,#f7941d 10%,#75c045 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */ filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#a94442' , endColorstr='#75c045' ,GradientType=1 ); /* IE6-9 */ ">
        &nbsp;
        <div style="z-index:1; vertical-align:middle; display:inline-block; background-color:#fff; width:30%; height: 30px; float:right; font-weight: bold; font-size:1.3em; color: #1375bc; text-align: left; padding: 6px;">70%<sup>*</sup></div>
    </div>
</div>
<div class="css-table" style="width: 500px; margin-bottom:10px;">
    <div class="col" style="height:30px; padding:6px; font-size:1.3em;"><strong>2016</strong></div>
    <div class="col" style="z-index:0; vertical-align:middle; width: 100%; height: 30px; padding:0; background: #a94442; /* Old browsers */
background: -moz-linear-gradient(left, #a94442 0%, #f7941d 10%, #75c045 100%); /* FF3.6-15 */
background: -webkit-linear-gradient(left, #a94442 0%,#f7941d 10%,#75c045 100%); /* Chrome10-25,Safari5.1-6 */
background: linear-gradient(to right, #a94442 0%,#f7941d 10%,#75c045 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#a94442', endColorstr='#75c045',GradientType=1 ); /* IE6-9 */">
        &nbsp;
        <div style="z-index:1; vertical-align:middle; display:inline-block; background-color:#fff; width:34%; height: 30px; float:right; font-weight: bold; font-size:1.3em; color: #1375bc; text-align: left; padding: 6px;">66%</div>
    </div>
</div>
<p class="figcaption"><sup>*</sup>Current as of 2.00pm 31 August 2017</p>