<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Related links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true "></i><a href="https://systemaccess.health.qld.gov.au">Update your details</a> | <a href="/outlook/html/training.htm#details">Guide</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true "></i><a href="/payroll-assistance/html/contacts.htm">Payroll service centres</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true "></i><a href="https://www.health.qld.gov.au/employment/job-search/hhs-recruitment-contact">Local recruitment units</a></li>
        </ul>
    </div>
</div>
<!-- END Related links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">To advise of changes</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i>Liz John, HR Connect</li>
            <li><i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><a href="mailto:liz.johnt@health.qld.gov.au">email</a></li>
            <li><i class="fa-li fa fa-phone fa-lg" aria-hidden="true"></i>(07) 3708 5079</li>
        </ul>
    </div>
</div>
<!-- END Contact section -->