<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Related links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true "></i><a href="/safety/sms/home.htm">Safety Management System</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true "></i><a href="/safety/employees/incident_reporting.htm">Reporting an Incident</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true "></i><a href="/safety/communications/alerts_notices.htm">Safety Alerts, Notices and Information</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true "></i><a href="/safety/elearning.htm">Online learning environment</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true "></i><a href="/safety/communications/circulars.htm">Safety Circulars</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true "></i><a href="/safety/communications/newsletters.htm">Publications</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true "></i><a href="/ehealth">eHealth Qld</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true "></i><a href="/hsq-staff/hr/contacts.htm#hsq-safety-wellbeing">Health Support Queensland (HSQ)</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true "></i><a href="https://www.ambulance.qld.gov.au/contacts.html">Queensland Ambulance Service (QAS)</a></li>
        </ul>
    </div>
</div>
<!-- END Related links section -->
<!-- BEGIN Quick Links section -->
<!--
<div class="sidebar_section">
    <h3 class="sidebar">Spotlight</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <a href="/safety/safety_topics/strategic_plan/OrgHeathStratPlan.pdf"><img class="right_ads" alt="Organisational Health Strategic Plan 2012-2016" src="http://qheps.health.qld.gov.au/safety/images/ohs_reform.gif"></a>
            </li>
        </ul>
    </div>
</div>
-->
<!-- END Quick Links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-envelope fa-lg " aria-hidden="true "></i><a href="mailto:OHS@health.qld.gov.au">Email OHS</a></li>
            <li><i class="fa-li fa fa-envelope fa-lg " aria-hidden="true "></i><a href="mailto:HRConnect@health.qld.gov.au">Email HR Connect</a></li>
        </ul>
    </div>
</div>
<!-- END Contact section -->