<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Suporting resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/staff-health-wellbeing/staff-wellbeing/docs/mental-health-framework-2017.pdf">Workplace Mental Health and Wellbeing Framework</a> (PDF, 323kB)</li>
        </ul>
    </div>
</div>
<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/safety/employees/home.htm">Employee safety information</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/safety/employees/incident_reporting.htm">Report an incident or near miss</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/staff-health-wellbeing/staff-wellbeing/home.htm">Staff health &amp; wellbeing</a></li>
            <!-- <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/culture/sparks/10000-steps/default.htm">10,000 steps challenge</a></li> -->
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://workplaces.healthier.qld.gov.au/"><span style="font-weight:bolder;">Healthier. Happier.</span> Workplaces</a></li>
        </ul>
        </ul>
    </div>
</div>
<!-- END Quick Links section -->
<!-- END Quick Links section -->
<!-- BEGIN Quick Links section -->
<!-- <div class="sidebar_section">
  <h3 class="sidebar">Staff wellness survey</h3>
  <div class="quick_links">
    <ul class="fa-ul">
      <li><a href="/hr/staff-wellness/week/survey.htm" title="Take the Survey"><img src="/hr/staff-wellness/week/images/butt-take-the-survey-v2.jpg" alt="Take the Survey" /></a></li>
    </ul>
  </div>
</div> -->
<!-- END Quick Links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <!-- Customise with the sub-site's direct email contact -->
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><a href="mailto:ohs@health.qld.gov.au">ohs@health.qld.gov.au</a>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->