<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Overview and registration</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/learning/influencing-behaviours-for-success.htm" title="Influencing behaviours for success" </a>Influencing behaviours for success</li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/learning/influencing-behaviours-keynote.htm" title="Keynote">Keynote</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i>
                <a href="/hr/learning/influencing-behaviours-workshop-a.htm" title="Workshop A" title="Workshop A">Workshop A</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/learning/influencing-behaviours-workshop-b.htm" title="Workshop B">Workshop B</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/learning/influencing-behaviours-resources.htm" title="Resources">Resources</a></li>
        </ul>
    </div>
</div>
<!-- END Quick Links section -->
<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related information</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <!--<li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/learning/docs/sept-nov-2016-flyer.pdf" title="Sept to Nov training calendar schedule">Sept to Nov training calendar schedule</a> (PDF, 212KB)</li>-->
            <li><i class="fa-li fa fa-calendar-check-o fa-lg" aria-hidden="true"></i><a href="http://qheps.health.qld.gov.au/hr/learning/training-calendar.htm" title="Training calendar">Training calendar</a></li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="http://qheps.health.qld.gov.au/hr/learning/docs/cultural-success-factors.pdf" title="Cultural success factors">Cultural success factors</a> (PDF, 428KB)</li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.surveymonkey.com/r/3NZHSYB" title="Suggest future training topics">Suggest future training topics</a></li>
        </ul>
    </div>
</div>
<!-- END Quick Links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><strong><a href="mailto:CultureCapability@health.qld.gov.au">email us</a></strong>
                <!-- Customise with sub-site contact's direct email -->
            </li>
            <li>
                <!-- Customise with the sub-site's direct email contact -->
                <i class="fa-li fa fa-phone fa-lg" aria-hidden="true"></i><strong>Call us:</strong> (07) 3225 2426</a>
            </li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="https://www.yammer.com/health.qld.gov.au/#/threads/inGroup?type=in_group&amp;feedId=4713761" title="Leadership Development Yammer channel">Join us on Yammer</a></li>
        </ul>
    </div>
</div>
<!-- END Contact section -->