<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Supporting resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/learning/docs/january-june-2018.pdf">Training Calendar | Jan&ndash;Jun 2018</a> (PDF, 342kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/learning/docs/October-November-December-2017.pdf">Training Calendar | Oct&ndash;Dec 2017</a> (PDF, 310kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/learning/docs/how-to-register.pdf">How to register for an event</a> (PDF, 276kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/learning/docs/How-to-cancel-rego.pdf">How to cancel your registration</a> (PDF, 354kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/learning/docs/how-to-get-login-details.pdf">How to get your login details</a> (PDF, 361kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/learning/docs/ceb-registration.pdf">How to register for a CEB webinar</a> (PDF, 107kB)</li>
        </ul>
    </div>
</div>
<!-- END Quick Links section -->
<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.surveymonkey.com/r/3NZHSYB">Suggest future training topics</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/onboarding/orientation/home.htm">Employee orientation</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/onboarding/mandatory.htm">Mandatory training</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.health.qld.gov.au/cunninghamcentre/html/courses/044">Admin Officers' Incentive Fund</a></li>
        </ul>
    </div>
</div>
<!-- END Quick Links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><strong><a href="mailto:CultureCapability@health.qld.gov.au">email Culture &amp; Capability</a></strong>
                <!-- Customise with sub-site contact's direct email -->
            </li>
            <li>
                <!-- Customise with the sub-site's direct email contact -->
                <i class="fa-li fa fa-phone fa-lg" aria-hidden="true"></i><strong>Call us:</strong> (07) 3708 5150</a>
            </li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i><a href="https://www.yammer.com/health.qld.gov.au/#/threads/inGroup?type=in_group&amp;feedId=4713761" title="Leadership Development Yammer channel">Join us on Yammer</a></li>
        </ul>
    </div>
</div>
<!-- END Contact section -->