<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Quick Links section-->
<div class="sidebar_section">
    <h3 class="sidebar">Supporting resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i>
                <a href="/hr/pay-leave-benefits/docs/choose-your-super-fund-form.pdf">Choose your super fund form</a> (PDF, 568kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i>
                <a href="/hr/pay-leave-benefits/docs/financial-advisor-questions.pdf">Questions you may wish to ask your financial advisor</a> (PDF, 52kB)</li>
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i>
                <a href="/hr/pay-leave-benefits/docs/concessional-limits.pdf">Concessional and non-concessional limits</a> (PDF, 55kB)</li>
        </ul>
    </div>
</div>
<!--END Quick Links section -->
<!-- BEGIN Quick Links section-->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i>
                <a href="https://www.forgov.qld.gov.au/superannuation">Choice of Superannuation fund</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i>
                <a href="https://qsuper.qld.gov.au/campaign/opentoall">QSuper website</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i>
                <a href="https://www.moneysmart.gov.au">ASIC MoneySmart website</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i>
                <a href="https://www.ato.gov.au/individuals/super/getting-started/employees">Australian Tax Office</a></li>
            <li><i class="fa-li fa fa-globe fa-lg" aria-hidden="true"></i>
                <a href="https://superfundlookup.gov.au/">Super Fund Lookup</a></li>
        </ul>
    </div>
</div>
<!--END Quick Links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section ">
    <h3 class="sidebar ">Need more help?</h3>
    <div class="quick_links ">
        <ul class="fa-ul ">
            <li>
                <i class="fa-li fa fa-envelope fa-lg " aria-hidden="true "></i><strong><a href="mailto:HRConnect@health.qld.gov.au ">Email us</a></strong>
                <!-- Customise with sub-site contact's direct email -->
            </li>
            <li>
                <i class="fa-li fa fa-address-book fa-lg " aria-hidden="true "></i><strong><a href="/hr/contact/local-hr-contacts.htm ">Contact your local HR</a></strong>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->