<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->

<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
  <h3 class="sidebar">Resources</h3>
  <div class="quick_links">
    <ul class="fa-ul"> <!-- TODO: populate all links below -->
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://elearn.com.au/qh/START.htm">Public Interest Disclosures online learning tool</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://elearn.com.au/qh/START.htm">Public Interest Disclosures online learning tool</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://elearn.com.au/qh/START.htm">Public Interest Disclosures online learning tool</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://elearn.com.au/qh/START.htm">Public Interest Disclosures online learning tool</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://elearn.com.au/qh/START.htm">Public Interest Disclosures online learning tool</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://elearn.com.au/qh/START.htm">Public Interest Disclosures online learning tool</a></li>
    </ul>
  </div>
</div>
<!-- END Quick Links section -->

<!-- BEGIN Quick Links section -->
<div class="sidebar_section">
  <h3 class="sidebar">More information</h3>
  <div class="quick_links">
    <ul class="fa-ul">
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://elearn.com.au/qh/START.htm">Public Interest Disclosures online learning tool</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://elearn.com.au/qh/START.htm">Public Interest Disclosures online learning tool</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://elearn.com.au/qh/START.htm">Public Interest Disclosures online learning tool</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://elearn.com.au/qh/START.htm">Public Interest Disclosures online learning tool</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://elearn.com.au/qh/START.htm">Public Interest Disclosures online learning tool</a></li>
        <li><i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="http://elearn.com.au/qh/START.htm">Public Interest Disclosures online learning tool</a></li>
    </ul>
  </div>
</div>
<!-- END Quick Links section -->

<!-- BEGIN Contact section -->
<div class="sidebar_section">
  <h3 class="sidebar">Need more help?</h3>
  <div class="quick_links">
    <ul class="fa-ul">
      <li>
        <i class="fa-li fa fa-address-book fa-lg" aria-hidden="true"></i><strong><a href="/hr/contact/local-hr-contacts.htm">Contact your local HR</a></strong>
      </li>
    </ul>
  </div>
</div>
<!-- END Contact section -->
