<!-- Customise the sidebar links below as appropriate. If migrating a pre-existing list, simply copy and replace the enclosing anchor tags for each link. -->
<!-- BEGIN Supporting resources section -->
<div class="sidebar_section">
    <h3 class="sidebar">Supporting resources</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-file-pdf-o fa-lg" aria-hidden="true"></i><a href="/hr/leadership/docs/poster-set.pdf">Poster set for your workplace</a> (PDF, 1.93MB)</li>
        </ul>
    </div>
</div>
<!-- END Supporting resources section -->
<!-- BEGIN Related links section -->
<div class="sidebar_section">
    <h3 class="sidebar">Related links</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/leadership/about.htm">Leadership Development Strategy</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/leadership/executives.htm">Executive development program</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/leadership/leaders.htm">Leader development program</a></li>
            <li><i class="fa-li fa fa-link fa-lg" aria-hidden="true"></i><a href="/hr/leadership/supervisors.htm">Supervisors development program</a></li>
        </ul>
    </div>
</div>
<!-- END Related links section -->
<!-- BEGIN Contact section -->
<div class="sidebar_section">
    <h3 class="sidebar">Need more help?</h3>
    <div class="quick_links">
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-envelope fa-lg" aria-hidden="true"></i><strong><a href="mailto:leadership-and-capability@health.qld.gov.au">Email us</a></strong>
                <!-- Customise with sub-site contact's direct email -->
            </li>
            <li>
                <!-- Customise with the sub-site's direct email contact -->
                <i class="fa-li fa fa-phone fa-lg" aria-hidden="true"></i>Call us: 323 <a href="tel:40621" class="tel">40621</a>
            </li>
            <li>
                <!-- Customise with the sub-site's direct email contact -->
                <i class="fa-li fa fa-circle fa-sm" aria-hidden="true"></i><a href="https://www.yammer.com/health.qld.gov.au/#/threads/inGroup?type=in_group&feedId=4713761">Join us on Yammer</a>
            </li>
        </ul>
    </div>
</div>
<!-- END Contact section -->